// Command genbook compiles the human-maintained opening source
// internal/book/openings.txt (SAN) into everything downstream:
//
//	internal/book/lines.go      — the generated Go book.Lines (UCI)
//	internal/book/bookblob.bin  — the resident blob (embedded by package book)
//	asm/book.inc                — layout defs for the asm probe
//
// openings.txt is the SINGLE source of truth. genbook parses it, validates
// every line legal move-by-move through refchess (refusing an illegal or
// malformed line, naming the opening and bad move), then keys each position
// on the engine's 32-bit Zobrist hash (== asm HASH0-3).
//
// Run: go run ./cmd/genbook   (from the repo root)
package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/zellyn/chess6502/internal/book"
)

const openingsPath = "internal/book/openings.txt"

func main() {
	lines, err := parseOpenings(openingsPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, "genbook: parse failed:", err)
		os.Exit(1)
	}
	if err := writeLinesGo("internal/book/lines.go", lines); err != nil {
		fmt.Fprintln(os.Stderr, "genbook: writing lines.go:", err)
		os.Exit(1)
	}

	entries, names, err := book.Build(lines)
	if err != nil {
		fmt.Fprintln(os.Stderr, "genbook: build failed:", err)
		os.Exit(1)
	}
	blob := book.Encode(entries, names)

	// Round-trip sanity: the blob must parse back to the same entry count.
	bk, err := book.Load(blob)
	if err != nil {
		fmt.Fprintln(os.Stderr, "genbook: blob failed to reload:", err)
		os.Exit(1)
	}

	rawNames, tokNames := measureNameTables(names)

	if err := os.WriteFile("internal/book/bookblob.bin", blob, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "genbook:", err)
		os.Exit(1)
	}
	if err := os.WriteFile("asm/book.inc", []byte(asmHeader(len(entries), len(names), len(blob))), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "genbook:", err)
		os.Exit(1)
	}

	entriesBytes := len(entries) * book.EntryStride
	fmt.Printf("genbook: %s -> %d lines -> %d entries (%d bytes), %d names\n",
		openingsPath, len(lines), len(entries), entriesBytes, len(names))
	fmt.Printf("  header %d B + entries %d B + names %d B (raw) = %d B blob\n",
		book.HeaderSize, entriesBytes, rawNames, len(blob))
	fmt.Printf("  name-table measurement: raw=%d B  word-tokenized=%d B  -> using RAW\n",
		rawNames, tokNames)
	fmt.Printf("  resident footprint: %d / %d bytes (%.1f%% of the 8 KB hole)\n",
		len(blob), book.MaxSize, 100*float64(len(blob))/float64(book.MaxSize))
	fmt.Printf("  reload OK: %d entries, %d names\n", len(bk.Entries()), len(names))

	// The budget check comes LAST and after the breakdown is printed: when a
	// book overflows you need to see WHERE the bytes went (entries vs names)
	// to decide what to cut, and a bare "too big" line does not tell you.
	if len(blob) > book.MaxSize {
		fmt.Fprintf(os.Stderr, "genbook: blob %d bytes EXCEEDS the %d-byte resident budget by %d\n",
			len(blob), book.MaxSize, len(blob)-book.MaxSize)
		os.Exit(1)
	}
}

// measureNameTables reports both name-encoding sizes so the choice is
// data-driven (the task asks to measure both and pick). raw = the
// length-prefixed form actually shipped. tokenized = a word dictionary
// (each unique word stored once) plus per-name word-index lists; it only
// wins when names share many words AND the dictionary overhead is repaid.
func measureNameTables(names []string) (raw, tok int) {
	for _, n := range names {
		raw += 1 + len(n)
	}
	// Tokenized: dictionary of unique words + per-name [count][wordID...].
	wordID := map[string]int{}
	dict := 0
	for _, n := range names {
		for _, w := range strings.Fields(n) {
			if _, ok := wordID[w]; !ok {
				wordID[w] = len(wordID)
				dict += 1 + len(w) // length-prefixed dictionary word
			}
		}
	}
	tok = dict
	for _, n := range names {
		tok += 1 + len(strings.Fields(n)) // count byte + one wordID byte each
	}
	return raw, tok
}

func asmHeader(entryCount, nameCount, blobSize int) string {
	var b strings.Builder
	b.WriteString("; Generated by cmd/genbook. DO NOT EDIT.\n")
	b.WriteString("; Resident opening book layout. The blob loads ONCE at startup into\n")
	b.WriteString("; the verified-free hi-res page-1 hole ($2000-$3FFF) and stays resident.\n")
	b.WriteString("; Probe: compute HASH0-3 for the current position, binary-search the\n")
	b.WriteString("; sorted entry array on the 4-byte key, weighted-pick among equal-key\n")
	b.WriteString("; entries, then NAMEID -> current-opening byte.\n\n")
	fmt.Fprintf(&b, "BOOK_BASE      = $%04X   ; resident base address\n", book.BaseAddr)
	fmt.Fprintf(&b, "BOOK_MAGIC     = BOOK_BASE+%d   ; 2 bytes 'B','K'\n", 0)
	fmt.Fprintf(&b, "BOOK_COUNT     = BOOK_BASE+%d   ; word: entry count (%d)\n", 2, entryCount)
	fmt.Fprintf(&b, "BOOK_NAMEOFF   = BOOK_BASE+%d   ; word: base-relative name-table offset\n", 4)
	fmt.Fprintf(&b, "BOOK_NAMECT    = BOOK_BASE+%d   ; byte: name count (%d)\n", 6, nameCount)
	fmt.Fprintf(&b, "BOOK_STRIDE    = %d            ; entry stride in bytes\n", book.EntryStride)
	fmt.Fprintf(&b, "BOOK_ENTRIES   = BOOK_BASE+%d   ; first entry\n\n", book.HeaderSize)
	b.WriteString("; entry field offsets (from an entry base):\n")
	b.WriteString("BOOK_E_KEY     = 0    ; 4 bytes LE == HASH0..3\n")
	b.WriteString("BOOK_E_FROM    = 4    ; 0x88 from-square\n")
	b.WriteString("BOOK_E_TO      = 5    ; 0x88 to-square\n")
	b.WriteString("BOOK_E_FLAGS   = 6    ; move flags (bits 0-2 promo)\n")
	b.WriteString("BOOK_E_WEIGHT  = 7    ; weighted-pick weight\n")
	b.WriteString("BOOK_E_NAMEID  = 8    ; name-table index -> current-opening byte\n\n")
	b.WriteString("; build stats:\n")
	fmt.Fprintf(&b, "BOOK_ENTRY_COUNT = %d\n", entryCount)
	fmt.Fprintf(&b, "BOOK_NAME_COUNT  = %d\n", nameCount)
	fmt.Fprintf(&b, "BOOK_BLOB_SIZE   = %d\n", blobSize)
	return b.String()
}
