package main

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"strings"

	"github.com/zellyn/chess6502/internal/book"
	"github.com/zellyn/chess6502/internal/refchess"
)

// parseOpenings reads the human-maintained SAN source file and compiles it
// into book.Lines (UCI moves), validating EVERY move legal move-by-move
// through refchess. It refuses an illegal or malformed line, naming the
// opening and the offending move in the error.
//
// File grammar (see docs/book.md):
//   - blank lines are ignored;
//   - a line whose first non-space char is '#' is a comment; the '#' line
//     directly above a moves line supplies that opening's NAME;
//   - a moves line is "<ECO>: <SAN moves>", e.g.
//     "C78: 1. e4 e5 2. Nf3 Nc6 3. Bb5 a6". Move numbers ("1.", "2.") are
//     optional and ignored.
func parseOpenings(path string) ([]book.Line, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var lines []book.Line
	var pendingName string
	sc := bufio.NewScanner(bytes.NewReader(data))
	lineNo := 0
	for sc.Scan() {
		lineNo++
		t := strings.TrimSpace(sc.Text())
		if t == "" {
			continue
		}
		if strings.HasPrefix(t, "#") {
			// The last '#' line before a moves line is that opening's name;
			// earlier ones (section dividers, notes) are just comments.
			pendingName = strings.TrimSpace(t[1:])
			continue
		}
		colon := strings.IndexByte(t, ':')
		if colon < 0 {
			return nil, fmt.Errorf("%s:%d: expected \"ECO: moves\", got %q", path, lineNo, t)
		}
		eco := strings.TrimSpace(t[:colon])
		if !validECO(eco) {
			return nil, fmt.Errorf("%s:%d: %q is not a valid ECO code (want e.g. C78)", path, lineNo, eco)
		}
		if pendingName == "" {
			return nil, fmt.Errorf("%s:%d: opening %s has no name line — put \"# Name\" directly above it", path, lineNo, eco)
		}
		name := pendingName
		pendingName = ""
		moves, err := compileSAN(strings.Fields(t[colon+1:]))
		if err != nil {
			return nil, fmt.Errorf("%s:%d: %s (%s): %w", path, lineNo, name, eco, err)
		}
		lines = append(lines, book.Line{ECO: eco, Name: name, Moves: moves})
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}
	if len(lines) == 0 {
		return nil, fmt.Errorf("%s: no openings found", path)
	}
	return lines, nil
}

// validECO reports whether s is a well-formed ECO code (letter A-E, two
// digits), e.g. "C78" or "A09".
func validECO(s string) bool {
	if len(s) != 3 {
		return false
	}
	return s[0] >= 'A' && s[0] <= 'E' && s[1] >= '0' && s[1] <= '9' && s[2] >= '0' && s[2] <= '9'
}

// compileSAN walks the SAN tokens from the start position, resolving each
// against refchess's legal moves (which validates legality and rejects
// ambiguity), and returns the UCI move list. Move-number tokens ("1.",
// "12.") are stripped.
func compileSAN(tokens []string) ([]string, error) {
	pos, err := refchess.ParseFEN(refchess.StartFEN)
	if err != nil {
		return nil, err
	}
	var uci []string
	ply := 0
	for _, tok := range tokens {
		mvStr := stripMoveNumber(tok)
		if mvStr == "" {
			continue
		}
		ply++
		mv, err := pos.ParseSAN(mvStr)
		if err != nil {
			return nil, fmt.Errorf("ply %d %q: %w", ply, mvStr, err)
		}
		uci = append(uci, mv.String())
		if err := pos.Make(mv); err != nil {
			return nil, fmt.Errorf("ply %d %q: illegal: %w", ply, mvStr, err)
		}
	}
	if len(uci) == 0 {
		return nil, fmt.Errorf("no moves")
	}
	return uci, nil
}

// stripMoveNumber removes a leading move-number ("1.", "12.", or a glued
// "1.e4" -> "e4") from a token. A token that is only digits (a stray move
// number) collapses to "".
func stripMoveNumber(tok string) string {
	i := 0
	for i < len(tok) && tok[i] >= '0' && tok[i] <= '9' {
		i++
	}
	if i == 0 {
		return tok // no leading digits: an ordinary move like "e4" or "O-O"
	}
	if i < len(tok) && tok[i] == '.' {
		for i < len(tok) && tok[i] == '.' {
			i++
		}
		return tok[i:]
	}
	if i == len(tok) {
		return "" // pure number: a stray move number
	}
	return tok
}

// writeLinesGo regenerates internal/book/lines.go from the compiled lines,
// keeping the exported book.Lines API stable. The file is marked generated.
func writeLinesGo(path string, lines []book.Line) error {
	var b strings.Builder
	b.WriteString("// Code generated by \"go run ./cmd/genbook\" from internal/book/openings.txt.\n")
	b.WriteString("// DO NOT EDIT. To change the opening book, edit internal/book/openings.txt\n")
	b.WriteString("// and run: go run ./cmd/genbook\n\n")
	b.WriteString("package book\n\n")
	b.WriteString("// Line is one curated opening variation: an ECO code, a short human name\n")
	b.WriteString("// (\"Sicilian, Najdorf\") and the main-line moves in UCI. The human-\n")
	b.WriteString("// maintained source is internal/book/openings.txt (SAN); the compiler is\n")
	b.WriteString("// cmd/genbook, which validates every line legal move-by-move through\n")
	b.WriteString("// refchess and REFUSES to emit an illegal or malformed line.\n")
	b.WriteString("type Line struct {\n\tECO   string\n\tName  string\n\tMoves []string\n}\n\n")
	b.WriteString("// Lines is the compiled opening book (generated from openings.txt).\n")
	b.WriteString("var Lines = []Line{\n")
	for _, ln := range lines {
		fmt.Fprintf(&b, "\t{%q, %s, split(%s)},\n", ln.ECO, goString(ln.Name), goString(strings.Join(ln.Moves, " ")))
	}
	b.WriteString("}\n\n")
	b.WriteString("// split turns a space-separated UCI move list into a slice.\n")
	b.WriteString("func split(s string) []string {\n")
	b.WriteString("\tvar out []string\n")
	b.WriteString("\tstart := -1\n")
	b.WriteString("\tfor i := 0; i <= len(s); i++ {\n")
	b.WriteString("\t\tif i == len(s) || s[i] == ' ' {\n")
	b.WriteString("\t\t\tif start >= 0 {\n")
	b.WriteString("\t\t\t\tout = append(out, s[start:i])\n")
	b.WriteString("\t\t\t\tstart = -1\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t} else if start < 0 {\n")
	b.WriteString("\t\t\tstart = i\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn out\n")
	b.WriteString("}\n")
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// goString renders s as a Go double-quoted string literal, preserving
// UTF-8 (names like "Grünfeld"/"Réti") rather than \u-escaping it. Names
// never contain a double quote or backslash, so this is exact.
func goString(s string) string {
	if strings.ContainsAny(s, "\"\\\n") {
		// Defensive: fall back to a fully-escaped literal.
		return fmt.Sprintf("%q", s)
	}
	return "\"" + s + "\""
}
