; Resident opening-book probe (docs/book.md). A read-only addition to the
; move-selection path: at the root, BEFORE any search, compute HASH0-3 for
; the current position, binary-search the resident blob at $2000, and — on
; a key hit — weighted-pick among the equal-key moves and play it directly,
; with NO node search. The selection function is byte-for-byte identical to
; internal/book's Go Book.Probe(key, r) given the same 32-bit r (proven by
; internal/chesstest's asm==Go parity test).
;
; ZERO-COST GUARANTEE for the bookless engine: this file is APPENDED at the
; end of the CODE segment and reached only via its own entry point
; (bookentry), which the harness/bridge invokes solely when a book is
; loaded. The normal search entry ($4000) is not modified, so every
; existing test (which never loads a book, so $2000 has no 'BK' magic) runs
; the byte-identical search path — TestMicroAB grand totals are unchanged.
; On real hardware the resident engine's own move loop chains the two:
;   jsr evalinit / jsr bookprobe / bcs playbook / <normal search>.
;
; Layout constants (BOOK_BASE=$2000, stride 9, field offsets, counts) come
; from asm/book.inc, generated by cmd/genbook alongside the blob.

        .include "book.inc"

; --- Probe scratch --------------------------------------------------------
; The probe runs standalone from bookentry (evalinit has finished; no search
; is active), so it borrows the search/eval ZP scratch, all dead at the root
; before the first search node. It NEVER writes HASH0-3 ($DD-$E0, its key
; input). The only bytes it CLAIMS (documented in defs.inc) are CUROPENING
; ($3D), RUNPTR ($3E-$3F), BOOKRND ($0222-$0225, consumed) and BOOKHIT
; ($0226); everything below is borrowed.
BK_LO     = T0          ; $CB-$CC  binary-search lo (16-bit entry index)
BK_HI     = T2          ; $CD-$CE  binary-search hi (exclusive)
BK_MID    = MUL0        ; $CF-$D0  binary-search midpoint / midptr input
BK_IDX    = PSP0        ; $D2-$D3  run-scan entry index
BK_TOTAL  = PSP1        ; $D4-$D5  summed run weight (divisor)
BK_REM    = EVTMP       ; $D7-$D8  r mod total = weighted pick / running rem
BK_RUNLEN = MULCNT      ; $DA      equal-key run length (selection guard)
ENTPTR    = CURPTR      ; $24-$25  ZP pointer to the current entry

; --------------------------------------------------------------------------
; bookentry: harness/bridge entry for a standalone probe pass. Computes the
; root hash exactly as the search entry does (jsr evalinit), probes the
; book, and reports the outcome in BOOKHIT (1 = book move in BESTFROM/TO/
; FLAGS with CUROPENING = its NAMEID; 0 = no book / out of book -> caller
; runs the normal search). No language-card install: evalinit and the probe
; never touch the aux-bank TT primitives.
; --------------------------------------------------------------------------
bookentry:
        ldx #$FF
        txs
        jsr evalinit            ; root HASH0-3 (byte-identical to search entry)
        jsr bookprobe           ; C=1 -> hit
        lda #0
        rol                     ; A = carry: 1 = hit, 0 = miss
        sta BOOKHIT
        lda #0
        sta EXIT_TRAP
        brk

; --------------------------------------------------------------------------
; bookprobe: with HASH0-3 = the current position's key, probe the resident
; book. Returns C=1 on a hit (BESTFROM/BESTTO/BESTFLAGS + CUROPENING set),
; C=0 on a miss (no book present or key not found). Clobbers A,X,Y and the
; borrowed scratch above; preserves HASH0-3.
; --------------------------------------------------------------------------
bookprobe:
        lda BOOK_MAGIC          ; 'B','K' present? absent => no book
        cmp #'B'
        bne bpmiss1
        lda BOOK_MAGIC+1
        cmp #'K'
        bne bpmiss1

        ; lower_bound: lo=0, hi=count; find first entry with key >= target
        lda #0
        sta BK_LO
        sta BK_LO+1
        lda BOOK_COUNT
        sta BK_HI
        lda BOOK_COUNT+1
        sta BK_HI+1
        jmp bsloop
bpmiss1:                        ; near miss return (reached by the magic and
        clc                     ;  lower_bound-fail branches on both sides)
        rts
bsloop:
        lda BK_LO               ; while lo < hi
        cmp BK_HI
        lda BK_LO+1
        sbc BK_HI+1
        bcs bsdone              ; lo >= hi
        clc                     ; mid = (lo + hi) >> 1  (sum < 2*count fits 16b)
        lda BK_LO
        adc BK_HI
        sta BK_MID
        lda BK_LO+1
        adc BK_HI+1
        sta BK_MID+1
        lsr BK_MID+1
        ror BK_MID
        jsr midptr              ; ENTPTR = &entry[mid]
        jsr keycmp              ; C=1 if entryKey >= target
        bcs bshi
        clc                     ; entryKey < target: lo = mid + 1
        lda BK_MID
        adc #1
        sta BK_LO
        lda BK_MID+1
        adc #0
        sta BK_LO+1
        jmp bsloop
bshi:
        lda BK_MID              ; hi = mid
        sta BK_HI
        lda BK_MID+1
        sta BK_HI+1
        jmp bsloop
bsdone:
        lda BK_LO               ; lo == lower_bound; lo >= count => miss
        cmp BOOK_COUNT
        lda BK_LO+1
        sbc BOOK_COUNT+1
        bcs bpmiss1
        lda BK_LO               ; ENTPTR = &entry[lo]
        sta BK_MID
        lda BK_LO+1
        sta BK_MID+1
        jsr midptr
        jsr keyeq               ; entries[lo].Key == target?
        bne bpmiss1             ; not equal => miss

        ; hit: sum the weights of the contiguous equal-key run [lo, hi)
        lda ENTPTR              ; RUNPTR = run start (kept for the pick pass)
        sta RUNPTR
        lda ENTPTR+1
        sta RUNPTR+1
        lda BK_LO
        sta BK_IDX
        lda BK_LO+1
        sta BK_IDX+1
        lda #0
        sta BK_TOTAL
        sta BK_TOTAL+1
        sta BK_RUNLEN
sumloop:
        lda BK_IDX              ; idx < count?
        cmp BOOK_COUNT
        lda BK_IDX+1
        sbc BOOK_COUNT+1
        bcs sumdone
        jsr keyeq               ; key still == target?
        bne sumdone
        ldy #BOOK_E_WEIGHT      ; total += weight
        clc
        lda BK_TOTAL
        adc (ENTPTR),y
        sta BK_TOTAL
        lda BK_TOTAL+1
        adc #0
        sta BK_TOTAL+1
        inc BK_RUNLEN
        clc                     ; ENTPTR += stride
        lda ENTPTR
        adc #BOOK_STRIDE
        sta ENTPTR
        lda ENTPTR+1
        adc #0
        sta ENTPTR+1
        inc BK_IDX              ; idx++
        bne sumloop
        inc BK_IDX+1
        jmp sumloop
sumdone:
        jsr bookmod             ; BK_REM = BOOKRND mod BK_TOTAL  (== Go r % total)

        ; weighted pick: walk the run from RUNPTR subtracting weights, exactly
        ; like Go's Probe. pick < total is guaranteed, so a move is always
        ; selected; the runlen guard reproduces Go's "return last" fallback.
selloop:
        ldy #BOOK_E_WEIGHT
        lda BK_REM              ; pick < weight?  (16-bit pick vs byte weight)
        cmp (RUNPTR),y
        lda BK_REM+1
        sbc #0
        bcc selfound            ; pick < weight: take this entry
        dec BK_RUNLEN           ; last entry always selects (fallback)
        beq selfound
        sec                     ; pick -= weight
        lda BK_REM
        sbc (RUNPTR),y
        sta BK_REM
        lda BK_REM+1
        sbc #0
        sta BK_REM+1
        clc                     ; RUNPTR += stride
        lda RUNPTR
        adc #BOOK_STRIDE
        sta RUNPTR
        lda RUNPTR+1
        adc #0
        sta RUNPTR+1
        jmp selloop
selfound:
        ldy #BOOK_E_FROM        ; play the move directly (engine encoding)
        lda (RUNPTR),y
        sta BESTFROM
        ldy #BOOK_E_TO
        lda (RUNPTR),y
        sta BESTTO
        ldy #BOOK_E_FLAGS
        lda (RUNPTR),y
        sta BESTFLAGS
        ldy #BOOK_E_NAMEID
        lda (RUNPTR),y
        sta CUROPENING          ; "which opening am I in"
        sec                     ; C=1: hit
        rts

; --------------------------------------------------------------------------
; midptr: ENTPTR = BOOK_ENTRIES + BK_MID*9  (mid in 0..count-1; mid*9 < 2800,
; +$2008 stays inside the blob). Clobbers A. Preserves BK_MID.
; --------------------------------------------------------------------------
midptr:
        lda BK_MID
        sta ENTPTR
        lda BK_MID+1
        sta ENTPTR+1
        asl ENTPTR              ; *8
        rol ENTPTR+1
        asl ENTPTR
        rol ENTPTR+1
        asl ENTPTR
        rol ENTPTR+1
        clc                     ; + mid  (=> *9)
        lda ENTPTR
        adc BK_MID
        sta ENTPTR
        lda ENTPTR+1
        adc BK_MID+1
        sta ENTPTR+1
        clc                     ; + base of the entry array
        lda ENTPTR
        adc #<BOOK_ENTRIES
        sta ENTPTR
        lda ENTPTR+1
        adc #>BOOK_ENTRIES
        sta ENTPTR+1
        rts

; --------------------------------------------------------------------------
; keycmp: unsigned 32-bit compare entries[ENTPTR].Key vs HASH0-3 (both LE).
; Returns C=1 if entryKey >= target, C=0 if entryKey < target. Clobbers A,Y.
; --------------------------------------------------------------------------
keycmp:
        sec
        ldy #(BOOK_E_KEY+0)
        lda (ENTPTR),y
        sbc HASH0
        ldy #(BOOK_E_KEY+1)
        lda (ENTPTR),y
        sbc HASH1
        ldy #(BOOK_E_KEY+2)
        lda (ENTPTR),y
        sbc HASH2
        ldy #(BOOK_E_KEY+3)
        lda (ENTPTR),y
        sbc HASH3
        rts

; --------------------------------------------------------------------------
; keyeq: Z=1 iff entries[ENTPTR].Key == HASH0-3. Clobbers A,Y.
; --------------------------------------------------------------------------
keyeq:
        ldy #(BOOK_E_KEY+0)
        lda (ENTPTR),y
        cmp HASH0
        bne keyeqx
        ldy #(BOOK_E_KEY+1)
        lda (ENTPTR),y
        cmp HASH1
        bne keyeqx
        ldy #(BOOK_E_KEY+2)
        lda (ENTPTR),y
        cmp HASH2
        bne keyeqx
        ldy #(BOOK_E_KEY+3)
        lda (ENTPTR),y
        cmp HASH3               ; Z set iff all four bytes equal
keyeqx:
        rts

; --------------------------------------------------------------------------
; bookmod: BK_REM = BOOKRND (32-bit LE) mod BK_TOTAL (16-bit), by MSB-first
; shift/subtract long division (remainder only). Identical result to Go's
; r % total. CONSUMES (shifts out) BOOKRND. Clobbers A,X.
; --------------------------------------------------------------------------
bookmod:
        lda #0
        sta BK_REM
        sta BK_REM+1
        ldx #32
bmloop:
        asl BOOKRND             ; shift the 32-bit dividend left, MSB -> carry
        rol BOOKRND+1
        rol BOOKRND+2
        rol BOOKRND+3
        rol BK_REM              ; bring the MSB into the running remainder
        rol BK_REM+1
        bcs bmsub               ; partial >= 2^16 > total: must subtract
        lda BK_REM              ; else rem >= total?
        cmp BK_TOTAL
        lda BK_REM+1
        sbc BK_TOTAL+1
        bcc bmnext              ; rem < total: keep
bmsub:
        sec                     ; rem -= total
        lda BK_REM
        sbc BK_TOTAL
        sta BK_REM
        lda BK_REM+1
        sbc BK_TOTAL+1
        sta BK_REM+1
bmnext:
        dex
        bne bmloop
        rts
