; Resident opening-book probe (docs/book.md). A read-only addition to the
; move-selection path: at the root, BEFORE any search, compute HASH0-3 for
; the current position, binary-search the resident entry array in AUXILIARY
; RAM at $0800, and — on a key hit — weighted-pick among the equal-key moves
; and play it directly, with NO node search.
;
; WHY AUX, AND WHY $0800. The blob used to live at main $2000-$3FFF, which is
; the MAIN half of double hi-res page 1; the board renderer needs those 8 KB,
; so the book moved to aux. It first went to aux $0200 and then up to $0800,
; because MIXED MODE's four-row text window is 80-COLUMN text whose even
; columns are fetched from aux $0400-$07FF. $0800-$1FFF is 6,144 B between the
; text page and the DHGR aux half, and the header + entries are 5,705 B of it.
;
; The book's NAME TABLE is not here at all. It is in LANGUAGE CARD BANK 2, and
; the reason it can be is this file: NOTHING BELOW EVER READS IT. Only
; asm/m8.s's uibookname does, once per book move, and that runs at $E000 where
; the bank switch costs nothing. The copier in asm/m8.s does both moves at boot.
;
; WHAT THAT COSTS. This code runs from the engine image at main $4000, so it
; cannot simply turn RAMRD on: RAMRD switches every read of $0200-$BFFF
; INCLUDING INSTRUCTION FETCHES, and aux $4000-$BFFF is the transposition
; table. So the blob is read through bkfetch/bkhdr, two primitives in the same
; Language Card page ($D000) the transposition table's ttfetch already runs
; from, which copy one 9-byte entry (or the 8-byte header) into MAIN and leave
; the arithmetic below reading plain main memory. That keeps every comparison,
; every carry and every fallback byte-identical to what it was at $2000 — the
; probe's Go parity is a proof about the SELECTION, and the selection did not
; change. Cost: one jsr and 9 byte copies per entry examined, roughly 100
; entries per probe, once per move. The selection function is byte-for-byte identical to
; internal/book's Go Book.Probe(key, r) given the same 32-bit r (proven by
; internal/chesstest's asm==Go parity test).
;
; ZERO-COST GUARANTEE for the bookless engine: this file is APPENDED at the
; end of the CODE segment and reached only via its own entry point
; (bookentry), which the harness/bridge invokes solely when a book is
; loaded. The normal search entry ($4000) is not modified, so every
; existing test (which never loads a book, so aux BOOK_BASE has no 'BK'
; magic) runs the byte-identical search path — TestMicroAB grand totals are unchanged.
; On real hardware the resident engine's own move loop chains the two:
;   jsr evalinit / jsr bookprobe / bcs playbook / <normal search>.
;
; Layout constants (BOOK_BASE, stride 9, field offsets, counts) come from
; asm/book.inc, generated by cmd/genbook alongside the two blobs.

        .include "book.inc"

; --- Probe scratch --------------------------------------------------------
; The probe runs standalone from bookentry (evalinit has finished; no search
; is active), so it borrows the search/eval ZP scratch, all dead at the root
; before the first search node. It NEVER writes HASH0-3 ($DD-$E0, its key
; input). The only bytes it CLAIMS (documented in defs.inc) are CUROPENING
; ($3D), RUNPTR ($3E-$3F), BOOKRND ($0222-$0225, consumed) and BOOKHIT
; ($0226); everything below is borrowed.
BK_LO     = T0          ; $CB-$CC  binary-search lo (16-bit entry index)
BK_HI     = T2          ; $CD-$CE  binary-search hi (exclusive)
BK_MID    = MUL0        ; $CF-$D0  binary-search midpoint / midptr input
BK_IDX    = PSP0        ; $D2-$D3  run-scan entry index
BK_TOTAL  = PSP1        ; $D4-$D5  summed run weight (divisor)
BK_REM    = EVTMP       ; $D7-$D8  r mod total = weighted pick / running rem
BK_RUNLEN = MULCNT      ; $DA      equal-key run length (selection guard)
ENTPTR    = CURPTR      ; $24-$25  ZP pointer to the current entry, in AUX
BK_RUN    = RUNPTR      ; $3E-$3F  ZP pointer to the run's first entry, in AUX

; The two MAIN-RAM landing pads the aux primitives copy into. They sit in the
; free tail of page 3 ($030D-$03EF, documented in defs.inc), so they cost no
; zero page and nothing the engine or the UI uses. BKENT is read with absolute
; indexing (BKENT,y), which is both smaller and faster than the (ENTPTR),y it
; replaces -- the pointer arithmetic all happens in aux space now.
; They are placed ABOVE the Disk II boot ROM's own page-3 scratch: that ROM
; builds its denibble table at $0356-$03D5 (the top is $02D6+$FF, from its own
; `eor $02D6,y`) and uses $0300-$0355 as the 2-of-6 buffer on EVERY sector it
; reads -- and asm/m8.s re-enters it to chain-load stage 2. They are also below
; $03F2-$03F4, the Autostart reset vector and power-up byte that m8main writes.
; The margin above the ROM is ONE BYTE, which is why it is a gate
; (internal/delivery TestPage3Layout, which reads the ceiling out of the ROM
; image) and not a comment. defs.inc's blanket claim that "nothing is defined
; between UNDOPD's tail ($02B7) and PIECESQ ($0800)" is about the ENGINE's own
; allocations; it was never true of the boot ROM or the text page.
        .export BKENT, BKHDR    ; internal/delivery's TestPage3Layout reads
                                ;  these out of asm/engine.lbl and checks them
                                ;  against the Disk II ROM's own page-3 ceiling
BKENT     = $03D6       ; 9 bytes ($03D6-$03DE): one entry, copied from aux
BKHDR     = $03DF       ; 8 bytes ($03DF-$03E6): the blob header, from aux
BOOK_HDR_SIZE = BOOK_ENTRIES - BOOK_BASE

; --------------------------------------------------------------------------
; bookpg: the base PAGE the whole probe reads through — the ONE engine-image
; change the big book needs (docs/prorwts2-design.md §3.3). Defaults to the
; resident blob's page (aux $0800); the UI stores $40 here while its
; BIGBOOKOK latch is open, so the identical binary search / run walk /
; weighted pick reads the BIG BOOK in the idle transposition-table window
; instead. Both blobs share the page-aligned base and the 8-byte header, so
; the page byte is the entire difference. The engine never writes it, and a
; bookless run never reads it (the probe is reached only via bookentry), so
; every no-book tree — TestMicroAB above all — is byte-identical.
; --------------------------------------------------------------------------
        .export bookpg
bookpg: .byte >BOOK_BASE

; --------------------------------------------------------------------------
; bookentry: harness/bridge entry for a standalone probe pass. Computes the
; root hash exactly as the search entry does (jsr evalinit), probes the
; book, and reports the outcome in BOOKHIT (1 = book move in BESTFROM/TO/
; FLAGS with CUROPENING = its NAMEID; 0 = no book / out of book -> caller
; runs the normal search).
;
; It DOES install the language-card code now, exactly as engine.s's $4000
; entry does. It used to say it did not need to, and that was true while the
; blob was in main; the probe reads aux through bkfetch today, so an entry
; that skipped the install would jsr into whatever $D000 happened to hold.
; --------------------------------------------------------------------------
bookentry:
        ldx #$FF
        txs
        lda $C08B               ; LC bank 1, read RAM + write RAM
        lda $C08B
        lda #<__LCCODE_LOAD__
        sta ZPTR
        lda #>__LCCODE_LOAD__
        sta ZPTR+1
        lda #<__LCCODE_RUN__
        sta TTPTR
        lda #>__LCCODE_RUN__
        sta TTPTR+1
        ldx #>(__LCCODE_SIZE__ + 255)
        ldy #0
bklc:   lda (ZPTR),y
        sta (TTPTR),y
        iny
        bne bklc
        inc ZPTR+1
        inc TTPTR+1
        dex
        bne bklc
        jsr evalinit            ; root HASH0-3 (byte-identical to search entry)
        jsr bookprobe           ; C=1 -> hit
        lda #0
        rol                     ; A = carry: 1 = hit, 0 = miss
        sta BOOKHIT
        lda #0
        sta EXIT_TRAP
        brk

; --------------------------------------------------------------------------
; bookprobe: with HASH0-3 = the current position's key, probe the resident
; book. Returns C=1 on a hit (BESTFROM/BESTTO/BESTFLAGS + CUROPENING set),
; C=0 on a miss (no book present or key not found). Clobbers A,X,Y and the
; borrowed scratch above; preserves HASH0-3.
; --------------------------------------------------------------------------
bookprobe:
        jsr bkhdr               ; BKHDR = the blob's 8-byte header, from aux
        lda BKHDR+0             ; 'B','K' present? absent => no book
        cmp #'B'
        bne bpmiss1
        lda BKHDR+1
        cmp #'K'
        bne bpmiss1

        ; lower_bound: lo=0, hi=count; find first entry with key >= target
        lda #0
        sta BK_LO
        sta BK_LO+1
        lda BKHDR+2             ; BOOK_COUNT
        sta BK_HI
        lda BKHDR+3
        sta BK_HI+1
        jmp bsloop
bpmiss1:                        ; near miss return (reached by the magic and
        clc                     ;  lower_bound-fail branches on both sides)
        rts
bsloop:
        lda BK_LO               ; while lo < hi
        cmp BK_HI
        lda BK_LO+1
        sbc BK_HI+1
        bcs bsdone              ; lo >= hi
        clc                     ; mid = (lo + hi) >> 1  (sum < 2*count fits 16b)
        lda BK_LO
        adc BK_HI
        sta BK_MID
        lda BK_LO+1
        adc BK_HI+1
        sta BK_MID+1
        lsr BK_MID+1
        ror BK_MID
        jsr midptr              ; ENTPTR = &entry[mid]
        jsr keycmp              ; C=1 if entryKey >= target
        bcs bshi
        clc                     ; entryKey < target: lo = mid + 1
        lda BK_MID
        adc #1
        sta BK_LO
        lda BK_MID+1
        adc #0
        sta BK_LO+1
        jmp bsloop
bshi:
        lda BK_MID              ; hi = mid
        sta BK_HI
        lda BK_MID+1
        sta BK_HI+1
        jmp bsloop
bsdone:
        lda BK_LO               ; lo == lower_bound; lo >= count => miss
        cmp BKHDR+2
        lda BK_LO+1
        sbc BKHDR+3
        bcs bpmiss1
        lda BK_LO               ; ENTPTR = &entry[lo]
        sta BK_MID
        lda BK_LO+1
        sta BK_MID+1
        jsr midptr
        jsr keyeq               ; entries[lo].Key == target?
        bne bpmiss1             ; not equal => miss

        ; hit: sum the weights of the contiguous equal-key run [lo, hi)
        lda ENTPTR              ; BK_RUN = run start (kept for the pick pass)
        sta BK_RUN
        lda ENTPTR+1
        sta BK_RUN+1
        lda BK_LO
        sta BK_IDX
        lda BK_LO+1
        sta BK_IDX+1
        lda #0
        sta BK_TOTAL
        sta BK_TOTAL+1
        sta BK_RUNLEN
sumloop:
        lda BK_IDX              ; idx < count?
        cmp BKHDR+2
        lda BK_IDX+1
        sbc BKHDR+3
        bcs sumdone
        jsr keyeq               ; key still == target?
        bne sumdone
        clc                     ; total += weight
        lda BK_TOTAL
        adc BKENT+BOOK_E_WEIGHT
        sta BK_TOTAL
        lda BK_TOTAL+1
        adc #0
        sta BK_TOTAL+1
        inc BK_RUNLEN
        clc                     ; ENTPTR += stride, and refill BKENT from it
        lda ENTPTR
        adc #BOOK_STRIDE
        sta ENTPTR
        lda ENTPTR+1
        adc #0
        sta ENTPTR+1
        jsr bkfetch
        inc BK_IDX              ; idx++
        bne sumloop
        inc BK_IDX+1
        jmp sumloop
sumdone:
        jsr bookmod             ; BK_REM = BOOKRND mod BK_TOTAL  (== Go r % total)

        ; weighted pick: walk the run from RUNPTR subtracting weights, exactly
        ; like Go's Probe. pick < total is guaranteed, so a move is always
        ; selected; the runlen guard reproduces Go's "return last" fallback.
        ; The run walk re-reads the run from its start, so ENTPTR goes back
        ; to BK_RUN and BKENT is refilled from there.
        lda BK_RUN
        sta ENTPTR
        lda BK_RUN+1
        sta ENTPTR+1
        jsr bkfetch
selloop:
        lda BK_REM              ; pick < weight?  (16-bit pick vs byte weight)
        cmp BKENT+BOOK_E_WEIGHT
        lda BK_REM+1
        sbc #0
        bcc selfound            ; pick < weight: take this entry
        dec BK_RUNLEN           ; last entry always selects (fallback)
        beq selfound
        sec                     ; pick -= weight
        lda BK_REM
        sbc BKENT+BOOK_E_WEIGHT
        sta BK_REM
        lda BK_REM+1
        sbc #0
        sta BK_REM+1
        clc                     ; ENTPTR += stride, and refill BKENT
        lda ENTPTR
        adc #BOOK_STRIDE
        sta ENTPTR
        lda ENTPTR+1
        adc #0
        sta ENTPTR+1
        jsr bkfetch
        jmp selloop
selfound:
        lda BKENT+BOOK_E_FROM   ; play the move directly (engine encoding)
        sta BESTFROM
        lda BKENT+BOOK_E_TO
        sta BESTTO
        lda BKENT+BOOK_E_FLAGS
        sta BESTFLAGS
        lda BKENT+BOOK_E_NAMEID
        sta CUROPENING          ; "which opening am I in"
        sec                     ; C=1: hit
        rts

; --------------------------------------------------------------------------
; midptr: ENTPTR = (bookpg:00 + 8) + BK_MID*9 (an AUX address; mid in
; 0..count-1, and both blobs cap count so base + 8 + mid*9 stays inside the
; blob — 5,705 B resident, 32,761 B big), then copy that entry into BKENT.
; The base page comes from bookpg; the header offset (+8) and the low base
; byte (0) are common to both blobs. Clobbers A,Y. Preserves BK_MID.
; --------------------------------------------------------------------------
midptr:
        lda BK_MID
        sta ENTPTR
        lda BK_MID+1
        sta ENTPTR+1
        asl ENTPTR              ; *8
        rol ENTPTR+1
        asl ENTPTR
        rol ENTPTR+1
        asl ENTPTR
        rol ENTPTR+1
        clc                     ; + mid  (=> *9)
        lda ENTPTR
        adc BK_MID
        sta ENTPTR
        lda ENTPTR+1
        adc BK_MID+1
        sta ENTPTR+1
        clc                     ; + base of the entry array: low byte is the
        lda ENTPTR              ;  8-byte header (both blobs), high byte is
        adc #<BOOK_ENTRIES      ;  the probe's base page
        sta ENTPTR
        lda ENTPTR+1
        adc bookpg
        sta ENTPTR+1
        jmp bkfetch             ; BKENT = the entry, copied out of aux
                                ;  (a tail call: bkfetch's rts returns to
                                ;   midptr's caller)

; --------------------------------------------------------------------------
; keycmp: unsigned 32-bit compare the FETCHED entry's Key vs HASH0-3 (both LE).
; Returns C=1 if entryKey >= target, C=0 if entryKey < target. Clobbers A.
; The caller must have fetched the entry into BKENT (midptr and the two walk
; loops all do).
; --------------------------------------------------------------------------
keycmp:
        sec
        lda BKENT+BOOK_E_KEY+0
        sbc HASH0
        lda BKENT+BOOK_E_KEY+1
        sbc HASH1
        lda BKENT+BOOK_E_KEY+2
        sbc HASH2
        lda BKENT+BOOK_E_KEY+3
        sbc HASH3
        rts

; --------------------------------------------------------------------------
; keyeq: Z=1 iff the FETCHED entry's Key == HASH0-3. Clobbers A. Same
; precondition as keycmp: BKENT holds the entry ENTPTR points at.
; --------------------------------------------------------------------------
keyeq:
        lda BKENT+BOOK_E_KEY+0
        cmp HASH0
        bne keyeqx
        lda BKENT+BOOK_E_KEY+1
        cmp HASH1
        bne keyeqx
        lda BKENT+BOOK_E_KEY+2
        cmp HASH2
        bne keyeqx
        lda BKENT+BOOK_E_KEY+3
        cmp HASH3               ; Z set iff all four bytes equal
keyeqx:
        rts

; --------------------------------------------------------------------------
; bookmod: BK_REM = BOOKRND (32-bit LE) mod BK_TOTAL (16-bit), by MSB-first
; shift/subtract long division (remainder only). Identical result to Go's
; r % total. CONSUMES (shifts out) BOOKRND. Clobbers A,X.
; --------------------------------------------------------------------------
bookmod:
        lda #0
        sta BK_REM
        sta BK_REM+1
        ldx #32
bmloop:
        asl BOOKRND             ; shift the 32-bit dividend left, MSB -> carry
        rol BOOKRND+1
        rol BOOKRND+2
        rol BOOKRND+3
        rol BK_REM              ; bring the MSB into the running remainder
        rol BK_REM+1
        bcs bmsub               ; partial >= 2^16 > total: must subtract
        lda BK_REM              ; else rem >= total?
        cmp BK_TOTAL
        lda BK_REM+1
        sbc BK_TOTAL+1
        bcc bmnext              ; rem < total: keep
bmsub:
        sec                     ; rem -= total
        lda BK_REM
        sbc BK_TOTAL
        sta BK_REM
        lda BK_REM+1
        sbc BK_TOTAL+1
        sta BK_REM+1
bmnext:
        dex
        bne bmloop
        rts

; --------------------------------------------------------------------------
; The two aux primitives. They live in the Language Card ($D000) for the same
; reason ttfetch does: RAMRD switches instruction fetches too, so the only
; code that may hold it on is code that is not fetched from $0200-$BFFF.
;
; Zero page follows ALTZP, not RAMRD, so (ENTPTR),y still reads its pointer
; out of MAIN zero page while the DATA byte comes from aux. Stores follow
; RAMWRT, which the caller must leave OFF -- with it on, the copy would land
; in aux and the probe would compare against main garbage. Every caller does
; (dhboard, m8bookaux and m8machine each restore it), and ttfetch has exactly
; the same precondition; it is written down here because it is a precondition
; and not an accident. That is the whole trick, and it is the one D4 records
; for the transposition table.
; --------------------------------------------------------------------------
        .segment "LCCODE"

; RAMWRT MUST BE OFF when either of these is called, and unlike ttfetch --
; whose comment says "exactly the same precondition" -- getting it wrong here
; is neither transient nor local. ttfetch's landing pad is main scratch, so a
; slipped switch misreads once. BKENT/BKHDR are $03D6-$03E6, and with RAMWRT
; on those stores land at AUX $03D6-$03E6, which is blob offset $01D6-$01E6:
; INSIDE ENTRIES 52-53 OF THE RESIDENT BOOK. One slip corrupts the book
; permanently, and every later probe whose binary search touches that range
; reads the damage. Nothing asserts the precondition at bookprobe entry, and
; the parity test runs with the switches at their power-on default -- so a
; regression here would pass every gate we have. What DOES catch it:
; chesstest.AsmBookProbe compares the whole aux blob against the bytes it
; poked, after every probe in the parity suite.
;
; bkfetch: BKENT = the 9-byte book entry at aux (ENTPTR). Clobbers A,Y.
bkfetch:
        sta $C003               ; RAMRD on
        ldy #BOOK_STRIDE-1
bkf1:   lda (ENTPTR),y
        sta BKENT,y
        dey
        bpl bkf1
        sta $C002               ; RAMRD off
        rts

; bkhdr: BKHDR = the blob's 8-byte header at aux bookpg:00. Clobbers A,Y —
; and ENTPTR, which it borrows as the aux pointer. That is new (the old body
; read the assembled-in BOOK_BASE absolute) and safe: its one caller,
; bookprobe, calls it FIRST, before the binary search gives ENTPTR a value.
; bookpg is read from MAIN (the engine image) BEFORE RAMRD goes on — with
; RAMRD on, a $4xxx read would fetch the transposition table instead.
bkhdr:
        lda bookpg
        sta ENTPTR+1
        lda #0
        sta ENTPTR
        sta $C003               ; RAMRD on
        ldy #BOOK_HDR_SIZE-1
bkh1:   lda (ENTPTR),y
        sta BKHDR,y
        dey
        bpl bkh1
        sta $C002               ; RAMRD off
        rts

        .segment "CODE"
