; Proof-of-concept driver for the double-hi-res board renderer (asm/dhgr.s).
;
; Runs the REAL renderer under the harness emulator from the address it will
; really run at: the stub at $4000 enables Language Card RAM exactly the way
; engine.s does, copies the UICODE segment to $E000, and jumps there. The
; renderer then paints the board from the position the Go test poked into
; BOARD, and exits.
;
; The Go side (internal/ui) pokes the position, pokes DHREP, runs the image,
; and reads back DHGR page 1 — aux $2000-$3FFF then main $2000-$3FFF, which
; is exactly the A2FC layout cmd/dhgr2png decodes. Running twice with
; different DHREP values yields the exact per-repaint cycle cost by
; difference, the same trick asm/uitest.s uses for the text renderer.

        .include "defs.inc"

DHREP   = $030D         ; poked: extra dhboard repaints, for cycle measurement

        .segment "CODE"

        .import __UICODE_LOAD__, __UICODE_RUN__, __UICODE_SIZE__

entry:  ldx #$FF
        txs
        cld
        lda $C08B               ; LC bank 1, read RAM + write RAM
        lda $C08B
        lda #<__UICODE_LOAD__
        sta ZPTR
        lda #>__UICODE_LOAD__
        sta ZPTR+1
        lda #<__UICODE_RUN__
        sta TTPTR
        lda #>__UICODE_RUN__
        sta TTPTR+1
        ldx #>(__UICODE_SIZE__ + 255)
        ldy #0
ldloop: lda (ZPTR),y
        sta (TTPTR),y
        iny
        bne ldloop
        inc ZPTR+1
        inc TTPTR+1
        dex
        bne ldloop
        jmp dhmain

; The tile blob lives in main RAM for this test (in the shipping build it is
; lifted into the otherwise entirely unused LC bank 2 at $D000). The renderer
; only ever reads it, so where it sits is a link-time detail.
        .segment "TILES"
DHTILES:
        .incbin "../internal/tiles/tileblob.bin"

        .segment "UICODE"

        .include "dhgr.s"

; ---- renderer data (uninitialised; dhinit fills all of it) ----
DHROWL: .res DHBOARDH
DHROWH: .res DHBOARDH
dhblnk: .res 2*DHTILESZ

; ---- the piece -> tile index table, generated by cmd/gentiles ----
        .include "tiles.inc"

; ---------------------------------------------------------------
; dhmain: set DHGR mixed mode, paint the board, then exit.
; ---------------------------------------------------------------
dhmain:
        ; Double hi-res needs, in this order: 80STORE on so the aux/main
        ; halves of $2000-$3FFF are reachable, 80COL on, AN3 off (DHIRES
        ; on), then GRAPHICS + HIRES + MIXED. We do NOT use 80STORE/PAGE2 to
        ; reach aux — we use RAMWRT, which is the discipline the engine
        ; already uses for the transposition table (docs/decisions.md D4) and
        ; the one goapple2's IIe model implements.
        sta $C00D               ; SET80COL
        sta $C05E               ; SETDHIRES (AN3 off)
        sta $C050               ; GRAPHICS
        sta $C057               ; HIRES
        sta $C053               ; MIXED — 160 scanlines of graphics, 4 text rows

        jsr dhinit
        jsr dhboard             ; the one repaint the screen assertion sees

        ; --- cycle measurement: DHREP extra repaints ---
        lda DHREP
        beq dhx
dhrep1: pha
        jsr dhboard
        pla
        sec
        sbc #1
        bne dhrep1
dhx:
        lda #0
        sta EXIT_TRAP
        brk
