// Package engsyms is the UI's symbol bridge: it turns the engine's ld65
// label file (asm/engine.lbl) into asm/engsyms.inc, a ca65 include of
// `ENG_name = $addr` equates for the exact set of engine entry points the
// on-device UI (asm/m8.s) calls.
//
// This is what keeps engine.bin bit-identical while a whole user interface
// grows beside it (docs/ui-design.md §8). The UI is a SEPARATE link that
// runs from Language Card RAM at $E000 and jsr's into the engine image by
// address; no engine source file is modified, so TestMicroAB stays green by
// construction and the UI costs the engine zero MAIN bytes.
//
// Wanted is a fixed whitelist rather than "dump every label": if an engine
// refactor renames or removes one of these, Generate fails loudly instead of
// silently linking the UI against a stale address (docs/ui-design.md §11
// risk 4 — the failure mode must be a broken build, never a wrong one).
package engsyms

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// Wanted is every engine symbol asm/m8.s references, with the reason.
var Wanted = map[string]string{
	"iterate":         "one full-window search at CURDEPTH (the UI drives ID itself)",
	"make":            "play FROM/TO/MVFLAGS, PLY++",
	"unmake":          "undo the move at PLY-1",
	"gennodef":        "full-width generate + per-ply move-list bookkeeping",
	"attacked":        "square-attacked test (the legality half of move validation)",
	"curincheck":      "is the side to move in check?",
	"evalinit":        "root accumulators, PHASE and HASH0-3 from the board",
	"bookprobe":       "resident opening-book probe (C=1 on a hit)",
	"checkclocks":     "FT2_SOFTCLK accumulating-clock entry point",
	"ccsite":          "the `jsr checkclock` whose operand FT2_SOFTCLK patches",
	"PCOSTLO":         "FT2_SOFTCLK per-phase cost table, low bytes",
	"PCOSTHI":         "FT2_SOFTCLK per-phase cost table, high bytes",
	"adaptmaybe":      "FT2_ADAPT post-iteration policy",
	"adaptaborthi":    "FT2_ADAPT hard-abort override (ABORTL = 2*CEILMAX)",
	"__LCCODE_LOAD__": "where the aux-bank TT primitives sit in the engine image",
	"__LCCODE_RUN__":  "where they must be copied to ($D000)",
	"__LCCODE_SIZE__": "how many bytes to copy",
}

// Parse reads an ld65 label file and returns the values of every Wanted
// symbol, erroring if any is absent.
func Parse(lblPath string) (map[string]uint32, error) {
	f, err := os.Open(lblPath)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	found := map[string]uint32{}
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		fields := strings.Fields(sc.Text()) // "al 004137 .iterate"
		if len(fields) != 3 || fields[0] != "al" || !strings.HasPrefix(fields[2], ".") {
			continue
		}
		name := fields[2][1:]
		if _, ok := Wanted[name]; !ok {
			continue
		}
		v, err := strconv.ParseUint(fields[1], 16, 32)
		if err != nil {
			continue
		}
		found[name] = uint32(v)
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}
	var missing []string
	for name := range Wanted {
		if _, ok := found[name]; !ok {
			missing = append(missing, name)
		}
	}
	if len(missing) > 0 {
		sort.Strings(missing)
		return nil, fmt.Errorf("engsyms: %s is missing engine symbols: %s",
			lblPath, strings.Join(missing, " "))
	}
	return found, nil
}

// Generate writes asm/engsyms.inc from asm/engine.lbl under root.
func Generate(root string) error {
	root, err := filepath.Abs(root)
	if err != nil {
		return err
	}
	lbl := filepath.Join(root, "asm", "engine.lbl")
	found, err := Parse(lbl)
	if err != nil {
		return err
	}
	names := make([]string, 0, len(found))
	for n := range found {
		names = append(names, n)
	}
	sort.Strings(names)

	var b bytes.Buffer
	fmt.Fprintf(&b, "; Generated by cmd/genengsyms (internal/engsyms) from asm/engine.lbl.\n")
	fmt.Fprintf(&b, "; DO NOT EDIT — regenerate whenever the engine is rebuilt.\n;\n")
	fmt.Fprintf(&b, "; Engine entry points the on-device UI (asm/m8.s) calls by address. The\n")
	fmt.Fprintf(&b, "; UI is a SEPARATE link running from Language Card RAM at $E000, so\n")
	fmt.Fprintf(&b, "; engine.bin is untouched by the UI's existence (docs/ui-design.md §8).\n\n")
	for _, n := range names {
		fmt.Fprintf(&b, "%-18s = $%04X   ; %s\n", "ENG_"+strings.Trim(n, "_"), found[n], Wanted[n])
	}
	return os.WriteFile(filepath.Join(root, "asm", "engsyms.inc"), b.Bytes(), 0o644)
}
