// Command gentiles slices the owner's hand-drawn DazzleDraw chessboard
// (assets/chess-dazzledraw-save.bin, A2FC: 8 KB aux then 8 KB main) into
// the resident per-square DHGR piece tiles:
//
//	internal/tiles/tileblob.bin  — the 24-tile blob (embedded by package tiles)
//	asm/tiles.inc                — layout defs + the TILEIDX dispatch table
//
// The artwork is the SINGLE source of truth: gentiles re-derives nothing
// by hand. Every geometric assumption the 76-byte tile format rests on
// (see package tiles' doc comment) is asserted against the actual pixels
// and the run FAILS if one is broken, so re-drawing the board can never
// silently produce a blob that renders garbage.
//
// Run: go run ./cmd/gentiles   (from the repo root, or via `make tiles`)
package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/zellyn/chess6502/internal/tiles"
)

const (
	artPath  = "assets/chess-dazzledraw-save.bin"
	blobPath = "internal/tiles/tileblob.bin"
	incPath  = "asm/tiles.inc"
)

func main() {
	art, err := os.ReadFile(artPath)
	if err != nil {
		fail(err)
	}
	blob, err := tiles.Build(art)
	if err != nil {
		fail(err)
	}
	if len(blob) != tiles.BlobSize {
		fail(fmt.Errorf("blob is %d bytes, want %d", len(blob), tiles.BlobSize))
	}
	if err := os.WriteFile(blobPath, blob, 0o644); err != nil {
		fail(err)
	}
	if err := os.WriteFile(incPath, []byte(asmInc()), 0o644); err != nil {
		fail(err)
	}

	fmt.Printf("gentiles: %s -> %d tiles of %dx%d dots\n", artPath, tiles.NumTiles, tiles.TileW, tiles.TileH)
	fmt.Printf("  %d rows x %d stored bytes = %d B/tile; blob = %d B -> %s\n",
		tiles.TileH, tiles.TileBytes, tiles.TileStride, len(blob), blobPath)
	fmt.Printf("  dropped per tile row: byte columns 0 (aux0) and %d (main2), asserted pure background\n",
		tiles.TileCols-1)
	fmt.Printf("  empty squares synthesised from aux=$%02X main=$%02X (light) / $00 (dark)\n",
		tiles.BGAux, tiles.BGMain)
	fmt.Printf("  wrote %s (TILEIDX mirrors PIECECH: dark<<4 | piece&$0F)\n", incPath)
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "gentiles:", err)
	os.Exit(1)
}

// asmInc emits the generated layout constants and the dispatch tables.
func asmInc() string {
	var b strings.Builder
	b.WriteString("; Generated by cmd/gentiles. DO NOT EDIT.\n")
	b.WriteString("; DHGR board-tile layout. The blob (internal/tiles/tileblob.bin) holds\n")
	b.WriteString("; 24 piece tiles; the two EMPTY-square tiles are synthesised from the\n")
	b.WriteString("; background constants below, so no bytes are spent on them.\n")
	b.WriteString(";\n")
	b.WriteString("; A rendered square is TILE_PITCH dots = TILE_SQCOLS byte columns per\n")
	b.WriteString("; plane. TILE_PITCH is a multiple of 14, so every file lands on a byte\n")
	b.WriteString("; boundary AND keeps the light-square dither phase: no shifting, ever.\n")
	b.WriteString(";\n")
	b.WriteString("; Per tile row the six byte columns are [aux0 aux1 aux2 main0 main1\n")
	b.WriteString("; main2]; columns 0 and 5 are pure background in ALL 24 tiles (asserted\n")
	b.WriteString("; by the generator), so only columns 1..4 are stored. Draw one row as:\n")
	b.WriteString(";   aux+0 = BG    aux+1,+2 = tile[0],tile[1]\n")
	b.WriteString(";   main+0,+1 = tile[2],tile[3]    main+2 = BG\n\n")

	fmt.Fprintf(&b, "TILE_PITCH     = %d      ; dots per square (destination), = 6 DHGR bytes\n", tiles.TileW)
	fmt.Fprintf(&b, "TILE_ROWS      = %d      ; scanlines per square\n", tiles.TileH)
	fmt.Fprintf(&b, "TILE_SQCOLS    = %d       ; byte columns per square PER PLANE (aux, main)\n", tiles.TileCols/2)
	fmt.Fprintf(&b, "TILE_BYTES     = %d       ; stored bytes per tile row (aux1,aux2,main0,main1)\n", tiles.TileBytes)
	fmt.Fprintf(&b, "TILE_STRIDE    = %d      ; bytes per tile (TILE_BYTES*TILE_ROWS)\n", tiles.TileStride)
	fmt.Fprintf(&b, "TILE_COUNT     = %d      ; piece tiles in the blob\n", tiles.NumTiles)
	fmt.Fprintf(&b, "TILE_BLOB_SIZE = %d    ; TILE_COUNT*TILE_STRIDE\n", tiles.BlobSize)
	fmt.Fprintf(&b, "TILE_BG_AUX    = $%02X     ; light-square dither, aux plane\n", tiles.BGAux)
	fmt.Fprintf(&b, "TILE_BG_MAIN   = $%02X     ; light-square dither, main plane\n", tiles.BGMain)
	fmt.Fprintf(&b, "TILE_BG_DARK   = $00     ; dark squares are simply blank\n")
	fmt.Fprintf(&b, "TILE_NONE      = $%02X     ; TILEIDX entry: empty square, draw background only\n\n", noTile)

	b.WriteString("; ---------------------------------------------------------------\n")
	b.WriteString("; TILEIDX / TILEOFFL / TILEOFFH: indexed EXACTLY like PIECECH, by\n")
	b.WriteString(";   dark<<4 | (piece & $0F)\n")
	b.WriteString("; TILEOFFL/H give the tile's byte offset from the blob base, so the\n")
	b.WriteString("; renderer never multiplies by TILE_STRIDE (=76, not a power of two).\n")
	b.WriteString("; ---------------------------------------------------------------\n")
	emitTable(&b, "TILEIDX", func(idx int) int {
		if idx < 0 {
			return noTile
		}
		return idx
	})
	emitTable(&b, "TILEOFFL", func(idx int) int {
		if idx < 0 {
			return 0
		}
		return (idx * tiles.TileStride) & 0xFF
	})
	emitTable(&b, "TILEOFFH", func(idx int) int {
		if idx < 0 {
			return 0
		}
		return (idx * tiles.TileStride) >> 8
	})
	return b.String()
}

// noTile marks an empty (or impossible) board nibble: draw background.
const noTile = 0xFF

// rowNames labels the six .byte lines, mirroring PIECECH's commentary.
var rowNames = []struct {
	first, last byte
	comment     string
}{
	{0x00, 0x00, "empty"},
	{0x01, 0x06, "wP wN wB wR wQ wK"},
	{0x07, 0x08, "impossible"},
	{0x09, 0x0E, "bP bN bB bR bQ bK"},
	{0x0F, 0x0F, "impossible"},
}

// emitTable writes a 32-entry table indexed by dark<<4|nibble, calling
// val with the blob tile index (-1 for empty/impossible).
func emitTable(b *strings.Builder, name string, val func(idx int) int) {
	fmt.Fprintf(b, "%s:\n", name)
	for _, dark := range []bool{false, true} {
		if dark {
			b.WriteString("        ; --- dark squares ---\n")
		} else {
			b.WriteString("        ; --- light squares ---\n")
		}
		hi := byte(0)
		if dark {
			hi = 0x10
		}
		for _, rn := range rowNames {
			var parts []string
			for n := rn.first; n <= rn.last; n++ {
				parts = append(parts, fmt.Sprintf("$%02X", val(tiles.TileIndex(n, dark))))
			}
			fmt.Fprintf(b, "        .byte %-23s ; $%02X-$%02X %s\n",
				strings.Join(parts, ","), hi|rn.first, hi|rn.last, rn.comment)
		}
	}
	b.WriteString("\n")
}
