package tiles

import _ "embed"

//go:embed tileblob.bin
var defaultBlob []byte

// DefaultBlob returns the raw embedded tile blob (generated by
// cmd/gentiles from assets/chess2-dazzledraw-save.bin).
func DefaultBlob() []byte { return defaultBlob }
