package book

import _ "embed"

//go:embed bookblob.bin
var defaultBlob []byte

// Default parses the embedded resident blob (generated by cmd/genbook).
func Default() (*Book, error) { return Load(defaultBlob) }

// DefaultBlob returns the raw embedded blob bytes.
func DefaultBlob() []byte { return defaultBlob }
