package book

import _ "embed"

// The two resident pieces, generated by cmd/genbook. They are separate files
// because they are separate DELIVERIES: bookblob.bin is copied to aux $0800
// and booknames.bin into Language Card bank 2. internal/delivery names each
// one and gives it its own landing zone.

//go:embed bookblob.bin
var defaultBlob []byte

//go:embed booknames.bin
var defaultNames []byte

// Default parses the embedded resident pieces (generated by cmd/genbook).
func Default() (*Book, error) { return Load(defaultBlob, defaultNames) }

// DefaultEntries returns the raw embedded ENTRIES bytes: header + entry
// array, the piece that goes resident in AUX at BaseAddr.
func DefaultEntries() []byte { return defaultBlob }

// DefaultNames returns the raw embedded NAME TABLE bytes: the piece that goes
// resident in Language Card bank 2 at NamesAddr.
func DefaultNames() []byte { return defaultNames }
