package book

import _ "embed"

// The two resident pieces, generated by cmd/genbook. They are separate files
// because they are separate DELIVERIES: bookblob.bin is copied to aux $0800
// and booknames.bin into Language Card bank 2. internal/delivery names each
// one and gives it its own landing zone.

//go:embed bookblob.bin
var defaultBlob []byte

//go:embed booknames.bin
var defaultNames []byte

//go:embed bigbook.bin
var defaultBig []byte

// Default parses the embedded resident pieces (generated by cmd/genbook).
func Default() (*Book, error) { return Load(defaultBlob, defaultNames) }

// DefaultEntries returns the raw embedded ENTRIES bytes: header + entry
// array, the piece that goes resident in AUX at BaseAddr.
func DefaultEntries() []byte { return defaultBlob }

// DefaultNames returns the raw embedded NAME TABLE bytes: the piece that goes
// resident in Language Card bank 2 at NamesAddr.
func DefaultNames() []byte { return defaultNames }

// DefaultBig returns the raw embedded BIG BOOK bytes: the same header + entry
// layout as the resident blob (so the asm probe walks it unchanged from a
// different base page), followed by a 16-bit checksum trailer, loaded from
// disk into the idle transposition-table window at aux BigBase. Generated by
// cmd/genbook alongside the resident pieces.
func DefaultBig() []byte { return defaultBig }

// DefaultBigBook parses the big blob (the trailer is ignored by Load, which
// reads the entry count from the header). It shares the resident name table.
func DefaultBigBook() (*Book, error) { return Load(defaultBig, defaultNames) }
