// Code generated by "go run ./cmd/genbook" from internal/book/openings.txt.
// DO NOT EDIT. To change the opening book, edit internal/book/openings.txt
// and run: go run ./cmd/genbook

package book

// Line is one curated opening variation: an ECO code, a short human name
// ("Sicilian, Najdorf") and the main-line moves in UCI. The human-
// maintained source is internal/book/openings.txt (SAN); the compiler is
// cmd/genbook, which validates every line legal move-by-move through
// refchess and REFUSES to emit an illegal or malformed line.
//
// Side selects WHOSE moves in the line become book entries: SideBoth (the
// default, written with a bare ECO code) takes every move, so the engine
// will both play the line and answer it. SideBlack ("A00/b") takes only
// Black's moves and SideWhite ("A00/w") only White's — that is how a
// breadth line can teach the engine to ANSWER 1.g4 without teaching it to
// PLAY 1.g4.
type Line struct {
	ECO   string
	Name  string
	Side  Side
	Moves []string
}

// Lines is the compiled opening book (generated from openings.txt).
var Lines = []Line{
	{"C78", "Ruy Lopez, Morphy", SideBoth, split("e2e4 e7e5 g1f3 b8c6 f1b5 a7a6 b5a4 g8f6 e1g1 f8e7 f1e1 b7b5 a4b3 d7d6")},
	{"C88", "Ruy Lopez, Closed", SideBoth, split("e2e4 e7e5 g1f3 b8c6 f1b5 a7a6 b5a4 g8f6 e1g1 f8e7 f1e1 b7b5 a4b3 e8g8 c2c3 d7d6")},
	{"C89", "Ruy Lopez, Marshall", SideBoth, split("e2e4 e7e5 g1f3 b8c6 f1b5 a7a6 b5a4 g8f6 e1g1 f8e7 f1e1 b7b5 a4b3 e8g8 c2c3 d7d5")},
	{"C67", "Ruy Lopez, Berlin", SideBoth, split("e2e4 e7e5 g1f3 b8c6 f1b5 g8f6 e1g1 f6e4 d2d4 f8e7 d1e2 e4d6")},
	{"C65", "Ruy Lopez, Berlin (d3)", SideBoth, split("e2e4 e7e5 g1f3 b8c6 f1b5 g8f6 d2d3 f8c5 c2c3 e8g8")},
	{"C50", "Italian, Giuoco Pianissimo", SideBoth, split("e2e4 e7e5 g1f3 b8c6 f1c4 f8c5 c2c3 g8f6 d2d3 d7d6 e1g1 e8g8")},
	{"C55", "Italian, Two Knights", SideBoth, split("e2e4 e7e5 g1f3 b8c6 f1c4 g8f6 d2d3 f8c5 c2c3 d7d6")},
	{"C45", "Scotch Game", SideBoth, split("e2e4 e7e5 g1f3 b8c6 d2d4 e5d4 f3d4 g8f6 b1c3 f8b4")},
	{"C42", "Petrov Defence", SideBoth, split("e2e4 e7e5 g1f3 g8f6 f3e5 d7d6 e5f3 f6e4 d2d4 d6d5 f1d3 b8c6")},
	{"C48", "Four Knights", SideBoth, split("e2e4 e7e5 g1f3 b8c6 b1c3 g8f6 f1b5 f8b4 e1g1 e8g8")},
	{"B90", "Sicilian, Najdorf", SideBoth, split("e2e4 c7c5 g1f3 d7d6 d2d4 c5d4 f3d4 g8f6 b1c3 a7a6")},
	{"B70", "Sicilian, Dragon", SideBoth, split("e2e4 c7c5 g1f3 d7d6 d2d4 c5d4 f3d4 g8f6 b1c3 g7g6")},
	{"B80", "Sicilian, Scheveningen", SideBoth, split("e2e4 c7c5 g1f3 d7d6 d2d4 c5d4 f3d4 g8f6 b1c3 e7e6")},
	{"B56", "Sicilian, Classical", SideBoth, split("e2e4 c7c5 g1f3 d7d6 d2d4 c5d4 f3d4 g8f6 b1c3 b8c6")},
	{"B33", "Sicilian, Sveshnikov", SideBoth, split("e2e4 c7c5 g1f3 b8c6 d2d4 c5d4 f3d4 g8f6 b1c3 e7e5")},
	{"B47", "Sicilian, Taimanov", SideBoth, split("e2e4 c7c5 g1f3 e7e6 d2d4 c5d4 f3d4 b8c6 b1c3 d8c7")},
	{"B41", "Sicilian, Kan", SideBoth, split("e2e4 c7c5 g1f3 e7e6 d2d4 c5d4 f3d4 a7a6 b1c3 d8c7")},
	{"B34", "Sicilian, Accelerated Dragon", SideBoth, split("e2e4 c7c5 g1f3 b8c6 d2d4 c5d4 f3d4 g7g6 b1c3 f8g7")},
	{"B31", "Sicilian, Rossolimo", SideBoth, split("e2e4 c7c5 g1f3 b8c6 f1b5 g7g6 e1g1 f8g7 f1e1 e7e5")},
	{"B22", "Sicilian, Alapin", SideBoth, split("e2e4 c7c5 c2c3 g8f6 e4e5 f6d5 d2d4 c5d4 g1f3 b8c6")},
	{"C18", "French, Winawer", SideBoth, split("e2e4 e7e6 d2d4 d7d5 b1c3 f8b4 e4e5 c7c5 a2a3 b4c3")},
	{"C11", "French, Classical", SideBoth, split("e2e4 e7e6 d2d4 d7d5 b1c3 g8f6 c1g5 f8e7 e4e5 f6d7")},
	{"C03", "French, Tarrasch", SideBoth, split("e2e4 e7e6 d2d4 d7d5 b1d2 g8f6 e4e5 f6d7 f1d3 c7c5")},
	{"C02", "French, Advance", SideBoth, split("e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 b8c6 g1f3 d8b6")},
	{"B18", "Caro-Kann, Classical", SideBoth, split("e2e4 c7c6 d2d4 d7d5 b1c3 d5e4 c3e4 c8f5 e4g3 f5g6")},
	{"B12", "Caro-Kann, Advance", SideBoth, split("e2e4 c7c6 d2d4 d7d5 e4e5 c8f5 g1f3 e7e6 f1e2 c6c5")},
	{"B13", "Caro-Kann, Exchange", SideBoth, split("e2e4 c7c6 d2d4 d7d5 e4d5 c6d5 f1d3 b8c6 c2c3 g8f6")},
	{"B01", "Scandinavian", SideBoth, split("e2e4 d7d5 e4d5 d8d5 b1c3 d5a5 d2d4 g8f6 g1f3 c7c6")},
	{"B07", "Pirc Defence", SideBoth, split("e2e4 d7d6 d2d4 g8f6 b1c3 g7g6 g1f3 f8g7 f1e2 e8g8")},
	{"B06", "Modern Defence", SideBoth, split("e2e4 g7g6 d2d4 f8g7 b1c3 d7d6 f2f4 g8f6 g1f3 e8g8")},
	{"B03", "Alekhine Defence", SideBoth, split("e2e4 g8f6 e4e5 f6d5 d2d4 d7d6 g1f3 g7g6 f1e2 f8g7")},
	{"D37", "Queen's Gambit Declined", SideBoth, split("d2d4 d7d5 c2c4 e7e6 b1c3 g8f6 g1f3 f8e7 c1f4 e8g8")},
	{"D20", "Queen's Gambit Accepted", SideBoth, split("d2d4 d7d5 c2c4 d5c4 g1f3 g8f6 e2e3 e7e6 f1c4 c7c5")},
	{"D15", "Slav Defence", SideBoth, split("d2d4 d7d5 c2c4 c7c6 g1f3 g8f6 b1c3 d5c4 a2a4 c8f5")},
	{"D45", "Semi-Slav", SideBoth, split("d2d4 d7d5 c2c4 c7c6 g1f3 g8f6 b1c3 e7e6 e2e3 b8d7")},
	{"D02", "London System", SideBoth, split("d2d4 d7d5 g1f3 g8f6 c1f4 c7c5 e2e3 b8c6 c2c3 d8b6")},
	{"E32", "Nimzo-Indian, Classical", SideBoth, split("d2d4 g8f6 c2c4 e7e6 b1c3 f8b4 d1c2 e8g8 a2a3 b4c3")},
	{"E15", "Queen's Indian", SideBoth, split("d2d4 g8f6 c2c4 e7e6 g1f3 b7b6 g2g3 c8a6 b2b3 f8b4")},
	{"E11", "Bogo-Indian", SideBoth, split("d2d4 g8f6 c2c4 e7e6 g1f3 f8b4 c1d2 d8e7")},
	{"E90", "King's Indian", SideBoth, split("d2d4 g8f6 c2c4 g7g6 b1c3 f8g7 e2e4 d7d6 g1f3 e8g8")},
	{"D85", "Grünfeld", SideBoth, split("d2d4 g8f6 c2c4 g7g6 b1c3 d7d5 c4d5 f6d5 e2e4 d5c3")},
	{"E06", "Catalan", SideBoth, split("d2d4 g8f6 c2c4 e7e6 g2g3 d7d5 f1g2 f8e7 g1f3 e8g8")},
	{"A30", "English, Symmetrical", SideBoth, split("c2c4 c7c5 g1f3 g8f6 b1c3 b8c6 g2g3 g7g6 f1g2 f8g7")},
	{"A28", "English, Four Knights", SideBoth, split("c2c4 e7e5 b1c3 g8f6 g1f3 b8c6 g2g3 f8b4")},
	{"A21", "English, Reversed Sicilian", SideBoth, split("c2c4 e7e5 b1c3 b8c6 g1f3 g8f6 g2g3 d7d5 c4d5 f6d5")},
	{"A09", "Réti Opening", SideBoth, split("g1f3 d7d5 c2c4 e7e6 g2g3 g8f6 f1g2 f8e7 e1g1 e8g8")},
	{"A07", "King's Indian Attack", SideBoth, split("g1f3 d7d5 g2g3 g8f6 f1g2 e7e6 e1g1 f8e7 d2d3 e8g8")},
	{"A90", "Dutch, Classical", SideBoth, split("d2d4 f7f5 g2g3 g8f6 f1g2 e7e6 g1f3 f8e7 e1g1 e8g8")},
	{"A00", "Irregular Opening", SideBlack, split("b2b3 d7d5 c1b2 g8f6 e2e3 e7e6 g1f3 f8e7")},
	{"A00", "Irregular Opening", SideBlack, split("b2b4 d7d5 c1b2 g8f6 e2e3 e7e6 g1f3 f8e7")},
	{"A03", "Bird Opening", SideBlack, split("f2f4 d7d5 g1f3 g8f6 e2e3 g7g6 f1e2 f8g7")},
	{"A00", "Irregular Opening", SideBlack, split("g2g3 d7d5 f1g2 g8f6 g1f3 e7e6")},
	{"A00", "Irregular Opening", SideBlack, split("b1c3 d7d5 d2d4 g8f6 c1f4 e7e6 g1f3 f8e7")},
	{"A00", "Irregular Opening", SideBlack, split("b1c3 d7d5 e2e4 d5d4 c3e2 e7e5 e2g3 c8e6")},
	{"A00", "Irregular Opening", SideBlack, split("e2e3 d7d5 d2d4 g8f6 g1f3 e7e6 f1d3 f8e7")},
	{"A00", "Irregular Opening", SideBlack, split("d2d3 d7d5 g1f3 g8f6 g2g3 e7e6 f1g2 f8e7")},
	{"A00", "Irregular Opening", SideBlack, split("c2c3 d7d5 d2d4 g8f6 g1f3 e7e6 c1f4 f8e7")},
	{"A00", "Grob Opening", SideBlack, split("g2g4 d7d5 f1g2 c7c6 h2h3 e7e5")},
	{"A00", "Irregular Opening", SideBlack, split("f2f3 d7d5 e2e4 d5e4 f3e4 e7e5 g1f3 b8c6")},
	{"A00", "Irregular Opening", SideBlack, split("a2a3 d7d5 d2d4 g8f6 g1f3 e7e6")},
	{"A00", "Irregular Opening", SideBlack, split("a2a4 d7d5 d2d4 g8f6 g1f3 e7e6")},
	{"A00", "Irregular Opening", SideBlack, split("h2h3 d7d5 d2d4 g8f6 g1f3 e7e6")},
	{"A00", "Irregular Opening", SideBlack, split("h2h4 d7d5 d2d4 g8f6 g1f3 e7e6")},
	{"A00", "Irregular Opening", SideBlack, split("b1a3 d7d5 d2d4 g8f6 g1f3 e7e6")},
	{"A00", "Irregular Opening", SideBlack, split("g1h3 d7d5 d2d4 g8f6 c1f4 e7e6")},
	{"A40", "Irregular Defence", SideWhite, split("e2e4 b8c6 d2d4 d7d5 b1c3 d5e4 d4d5 c6e5")},
	{"A40", "Irregular Defence", SideWhite, split("e2e4 b7b6 d2d4 c8b7 b1c3 e7e6 g1f3 d7d6")},
	{"A40", "Irregular Defence", SideWhite, split("e2e4 a7a6 d2d4 d7d5 b1c3 d5e4 c3e4")},
	{"B00", "Irregular Defence", SideWhite, split("e2e4 b7b5 f1b5 c8b7 b1c3 e7e6")},
	{"B00", "Irregular Defence", SideWhite, split("e2e4 f7f5 e4f5 g8f6 b1c3 d7d5")},
	{"B00", "Irregular Defence", SideWhite, split("e2e4 f7f6 d2d4 d7d5 b1c3 d5e4")},
	{"B00", "Irregular Defence", SideWhite, split("e2e4 g7g5 d2d4 d7d6 b1c3 f8g7")},
	{"B00", "Irregular Defence", SideWhite, split("e2e4 h7h5 d2d4 d7d5 b1c3 d5e4")},
	{"B00", "Irregular Defence", SideWhite, split("e2e4 h7h6 d2d4 d7d5 b1c3 d5e4")},
	{"B00", "Irregular Defence", SideWhite, split("e2e4 a7a5 d2d4 d7d5 b1c3 d5e4")},
	{"B00", "Irregular Defence", SideWhite, split("e2e4 b8a6 d2d4 d7d5 b1c3 d5e4")},
	{"B00", "Irregular Defence", SideWhite, split("e2e4 g8h6 d2d4 d7d5 b1c3 d5e4")},
	{"A40", "Queen's Gambit Declined", SideWhite, split("d2d4 e7e6 c2c4 d7d5 b1c3 g8f6 g1f3 f8e7")},
	{"B07", "Pirc Defence", SideWhite, split("d2d4 d7d6 e2e4 g8f6 b1c3 g7g6 g1f3 f8g7")},
	{"B06", "Modern Defence", SideWhite, split("d2d4 g7g6 e2e4 f8g7 b1c3 d7d6 f2f4 g8f6")},
	{"B18", "Caro-Kann Defence", SideWhite, split("d2d4 c7c6 e2e4 d7d5 b1c3 d5e4 c3e4 c8f5")},
	{"A40", "Irregular Defence", SideWhite, split("d2d4 c7c5 d4d5 e7e5 e2e4 d7d6 b1c3 f8e7")},
	{"A40", "English Defence", SideWhite, split("d2d4 b7b6 c2c4 c8b7 b1c3 e7e6 e2e4 f8b4")},
	{"A40", "Irregular Defence", SideWhite, split("d2d4 b8c6 d4d5 c6e5 e2e4 e7e6 b1c3 g8f6")},
	{"A40", "Irregular Defence", SideWhite, split("d2d4 e7e5 d4e5 b8c6 g1f3 d8e7 c1f4")},
	{"A40", "Irregular Defence", SideWhite, split("d2d4 b7b5 e2e4 c8b7 f1b5 b7e4 g1f3")},
	{"A40", "Irregular Defence", SideWhite, split("d2d4 f7f6 e2e4 d7d5 b1c3 d5e4")},
	{"A40", "Irregular Defence", SideWhite, split("d2d4 a7a6 e2e4 d7d5 b1c3 d5e4")},
	{"A40", "Irregular Defence", SideWhite, split("d2d4 h7h6 e2e4 d7d5 b1c3 d5e4")},
	{"A40", "Irregular Defence", SideWhite, split("d2d4 a7a5 e2e4 d7d5 b1c3 d5e4")},
	{"A40", "Irregular Defence", SideWhite, split("d2d4 h7h5 e2e4 d7d5 b1c3 d5e4")},
	{"A40", "Irregular Defence", SideWhite, split("d2d4 b8a6 e2e4 d7d5 b1c3 d5e4")},
	{"A40", "Irregular Defence", SideWhite, split("d2d4 g8h6 e2e4 d7d5 b1c3 d5e4")},
	{"A40", "Irregular Defence", SideWhite, split("d2d4 g7g5 e2e4 d7d6 b1c3 f8g7")},
	{"C20", "Open Game", SideBlack, split("e2e4 e7e5 b1c3 g8f6 f2f4 d7d5 f4e5 f6e4")},
	{"C20", "Open Game", SideBlack, split("e2e4 e7e5 f1c4 g8f6 d2d3 c7c6 g1f3 d7d5")},
	{"C30", "King's Gambit", SideBlack, split("e2e4 e7e5 f2f4 e5f4 g1f3 d7d5 e4d5 g8f6")},
	{"C20", "Open Game", SideBlack, split("e2e4 e7e5 d2d4 e5d4 d1d4 b8c6 d4e3 g8f6")},
	{"C20", "Open Game", SideBlack, split("e2e4 e7e5 d2d3 g8f6 g1f3 b8c6 f1e2 f8c5")},
	{"C20", "Open Game", SideBlack, split("e2e4 e7e5 c2c3 d7d5 e4d5 d8d5 d2d4 b8c6")},
	{"C20", "Open Game", SideBlack, split("e2e4 e7e5 d1h5 b8c6 f1c4 g7g6 h5f3 g8f6")},
	{"B20", "Sicilian Defence", SideBlack, split("e2e4 c7c5 b1c3 b8c6 g2g3 g7g6 f1g2 f8g7")},
	{"B20", "Sicilian Defence", SideBlack, split("e2e4 c7c5 d2d4 c5d4 c2c3 d4c3 b1c3 b8c6")},
	{"B20", "Sicilian Defence", SideBlack, split("e2e4 c7c5 f2f4 d7d5 e4d5 g8f6 b1c3 f6d5")},
	{"B20", "Sicilian Defence", SideBlack, split("e2e4 c7c5 b2b4 c5b4 a2a3 d7d5 e4d5 d8d5")},
	{"B20", "Sicilian Defence", SideBlack, split("e2e4 c7c5 g2g3 d7d5 e4d5 d8d5 g1f3 c8g4")},
	{"B20", "Sicilian Defence", SideBlack, split("e2e4 c7c5 g1e2 g8f6 b1c3 d7d5 e4d5 f6d5")},
	{"C00", "French Defence", SideBlack, split("e2e4 e7e6 b1c3 d7d5 g1f3 g8f6 e4e5 f6d7")},
	{"C00", "French Defence", SideBlack, split("e2e4 e7e6 g1f3 d7d5 b1c3 g8f6 e4e5 f6d7")},
	{"C00", "French Defence", SideBlack, split("e2e4 e7e6 d2d3 d7d5 b1d2 g8f6 g1f3 c7c5")},
	{"B10", "Caro-Kann Defence", SideBlack, split("e2e4 c7c6 b1c3 d7d5 g1f3 c8g4 h2h3 g4f3")},
	{"B10", "Caro-Kann Defence", SideBlack, split("e2e4 c7c6 g1f3 d7d5 b1c3 c8g4 h2h3 g4f3")},
	{"B10", "Caro-Kann Defence", SideBlack, split("e2e4 c7c6 c2c4 d7d5 e4d5 c6d5 c4d5 g8f6")},
	{"B10", "Caro-Kann Defence", SideBlack, split("e2e4 c7c6 d2d3 d7d5 b1d2 e7e5 g1f3 f8d6")},
	{"B07", "Pirc Defence", SideBlack, split("e2e4 d7d6 g1f3 g8f6 b1c3 g7g6 d2d4 f8g7")},
	{"B07", "Pirc Defence", SideBlack, split("e2e4 d7d6 b1c3 g8f6 d2d4 g7g6 g1f3 f8g7")},
	{"B06", "Modern Defence", SideBlack, split("e2e4 g7g6 b1c3 f8g7 d2d4 d7d6 f2f4 g8f6")},
	{"B06", "Modern Defence", SideBlack, split("e2e4 g7g6 g1f3 f8g7 d2d4 d7d6 b1c3 g8f6")},
	{"B02", "Alekhine Defence", SideBlack, split("e2e4 g8f6 b1c3 d7d5 e4e5 f6d7 d2d4 e7e6")},
	{"B02", "Alekhine Defence", SideBlack, split("e2e4 g8f6 d2d3 d7d5 b1d2 e7e5 g1f3 b8c6")},
	{"B02", "Alekhine Defence", SideBlack, split("e2e4 g8f6 e4e5 f6d5 c2c4 d5b6 d2d4 d7d6")},
	{"B02", "Alekhine Defence", SideBlack, split("e2e4 g8f6 e4e5 f6d5 g1f3 d7d6 d2d4 g7g6")},
	{"B02", "Alekhine Defence", SideBlack, split("e2e4 g8f6 e4e5 f6d5 d2d4 d7d6 c2c4 d5b6")},
	{"B01", "Scandinavian", SideBlack, split("e2e4 d7d5 b1c3 d5d4 c3e2 e7e5 e2g3 c8e6")},
	{"B01", "Scandinavian", SideBlack, split("e2e4 d7d5 e4e5 c7c5 d2d4 b8c6 g1f3 c8f5")},
	{"B01", "Scandinavian", SideBlack, split("e2e4 d7d5 e4d5 d8d5 g1f3 c8g4 f1e2 b8c6")},
	{"A45", "Indian Game", SideBlack, split("d2d4 g8f6 g1f3 e7e6 c2c4 b7b6")},
	{"D00", "Queen's Pawn Game", SideBlack, split("d2d4 g8f6 b1c3 d7d5 c1f4 e7e6 e2e3 f8d6")},
	{"A45", "London System", SideBlack, split("d2d4 g8f6 c1f4 e7e6 e2e3 c7c5 c2c3 b7b6")},
	{"A45", "Trompowsky Attack", SideBlack, split("d2d4 g8f6 c1g5 e7e6 e2e4 h7h6 g5f6 d8f6")},
	{"A45", "Indian Game", SideBlack, split("d2d4 g8f6 g2g3 g7g6 f1g2 f8g7 g1f3 e8g8")},
	{"A45", "Indian Game", SideBlack, split("d2d4 g8f6 e2e3 e7e6 g1f3 d7d5 c2c4 f8e7")},
	{"A45", "Indian Game", SideBlack, split("d2d4 g8f6 f2f4 d7d5 g1f3 e7e6 e2e3 c7c5")},
	{"D00", "Queen's Pawn Game", SideBlack, split("d2d4 d7d5 b1c3 g8f6 c1g5 e7e6 e2e4 f8e7")},
	{"D02", "London System", SideBlack, split("d2d4 d7d5 c1f4 g8f6 e2e3 e7e6 g1f3 c7c5")},
	{"D00", "Queen's Pawn Game", SideBlack, split("d2d4 d7d5 e2e3 g8f6 g1f3 e7e6 c2c4 f8e7")},
	{"D00", "Queen's Pawn Game", SideBlack, split("d2d4 d7d5 c1g5 h7h6 g5h4 c7c6 e2e3 d8b6")},
	{"D00", "Queen's Pawn Game", SideBlack, split("d2d4 d7d5 g2g3 g8f6 f1g2 e7e6 g1f3 f8e7")},
	{"D00", "Queen's Pawn Game", SideBlack, split("d2d4 d7d5 e2e4 d5e4 b1c3 g8f6 f2f3 e4f3")},
	{"A80", "Dutch Defence", SideBlack, split("d2d4 f7f5 c2c4 g8f6 b1c3 e7e6 g1f3 f8e7")},
	{"A80", "Dutch Defence", SideBlack, split("d2d4 f7f5 g1f3 g8f6 g2g3 e7e6 f1g2 f8e7")},
	{"A80", "Dutch Defence", SideBlack, split("d2d4 f7f5 e2e4 f5e4 b1c3 g8f6 c1g5 e7e6")},
	{"A56", "Benoni Defence", SideWhite, split("d2d4 g8f6 c2c4 c7c5 d4d5 e7e6 b1c3 e6d5 c4d5 d7d6")},
	{"A50", "Indian Defence", SideWhite, split("d2d4 g8f6 c2c4 c7c5 d4d5 b7b5 c4b5 a7a6 b5a6 c8a6")},
	{"A50", "Indian Defence", SideWhite, split("d2d4 g8f6 c2c4 d7d6 b1c3 e7e5 g1f3 b8d7")},
	{"A40", "English Defence", SideWhite, split("d2d4 g8f6 c2c4 b7b6 b1c3 c8b7 g1f3 e7e6")},
	{"A50", "Indian Defence", SideWhite, split("d2d4 g8f6 c2c4 b8c6 g1f3 e7e6 b1c3 f8b4")},
	{"D06", "Queen's Gambit", SideWhite, split("d2d4 g8f6 c2c4 d7d5 c4d5 f6d5 g1f3 e7e6")},
	{"D06", "Queen's Gambit", SideWhite, split("d2d4 d7d5 c2c4 b8c6 b1c3 d5c4 g1f3 g8f6")},
	{"D06", "Queen's Gambit", SideWhite, split("d2d4 d7d5 c2c4 c8f5 c4d5 f5b1 d1a4 c7c6")},
	{"D06", "Queen's Gambit", SideWhite, split("d2d4 d7d5 c2c4 c7c5 c4d5 g8f6 g1f3 c5d4")},
	{"D06", "Queen's Gambit", SideWhite, split("d2d4 d7d5 c2c4 g8f6 c4d5 f6d5 g1f3 e7e6")},
	{"D06", "Queen's Gambit", SideWhite, split("d2d4 d7d5 c2c4 e7e5 d4e5 d5d4 g1f3 b8c6")},
	{"C41", "Philidor Defence", SideWhite, split("e2e4 e7e5 g1f3 d7d6 d2d4 g8f6 b1c3 b8d7")},
	{"C40", "Open Game", SideWhite, split("e2e4 e7e5 g1f3 f7f5 f3e5 d8f6 d2d4 d7d6")},
	{"C40", "Open Game", SideWhite, split("e2e4 e7e5 g1f3 d7d5 e4d5 e5e4 d1e2 g8f6")},
	{"B20", "Sicilian Defence", SideWhite, split("e2e4 c7c5 g1f3 g8f6 e4e5 f6d5 b1c3 e7e6")},
	{"B27", "Sicilian Defence", SideWhite, split("e2e4 c7c5 g1f3 g7g6 d2d4 c5d4 f3d4 b8c6")},
	{"B27", "Sicilian Defence", SideWhite, split("e2e4 c7c5 g1f3 a7a6 c2c3 d7d5 e4d5 d8d5")},
	{"A15", "English Opening", SideWhite, split("c2c4 g8f6 b1c3 e7e6 g1f3 d7d5 d2d4 f8e7")},
	{"A10", "English Opening", SideWhite, split("c2c4 e7e6 b1c3 d7d5 d2d4 g8f6 g1f3 f8e7")},
	{"A11", "English, Anglo-Slav", SideWhite, split("c2c4 c7c6 g1f3 d7d5 b1c3 g8f6 d2d4 e7e6")},
	{"A10", "English, Anglo-Indian", SideWhite, split("c2c4 g7g6 d2d4 f8g7 b1c3 g8f6 e2e4 d7d6")},
	{"A10", "English, Anglo-Scandinavian", SideWhite, split("c2c4 d7d5 c4d5 d8d5 b1c3 d5a5 d2d4 g8f6")},
	{"A10", "English Opening", SideWhite, split("c2c4 b7b6 b1c3 c8b7 e2e4 e7e6 g1f3 f8b4")},
	{"A10", "English Opening", SideWhite, split("c2c4 f7f5 b1c3 g8f6 g2g3 e7e6 f1g2 f8e7")},
	{"A04", "Réti Opening", SideWhite, split("g1f3 g8f6 c2c4 e7e6 b1c3 d7d5 d2d4 f8e7")},
	{"A04", "Réti Opening", SideWhite, split("g1f3 c7c5 c2c4 b8c6 b1c3 g8f6 g2g3 g7g6")},
	{"A04", "Réti Opening", SideWhite, split("g1f3 f7f5 d2d4 g8f6 g2g3 e7e6 f1g2 f8e7")},
	{"A04", "Réti Opening", SideWhite, split("g1f3 d7d6 d2d4 g8f6 b1c3 g7g6 e2e4 f8g7")},
	{"A04", "Réti Opening", SideWhite, split("g1f3 e7e6 d2d4 d7d5 c2c4 g8f6 b1c3 f8e7")},
	{"A04", "Réti Opening", SideWhite, split("g1f3 g7g6 d2d4 f8g7 c2c4 g8f6 b1c3 d7d6")},
	{"D02", "London System", SideBlack, split("g1f3 d7d5 d2d4 g8f6 c1f4 c7c5 e2e3 b8c6")},
	{"A06", "Réti Opening", SideBlack, split("g1f3 d7d5 b1c3 g8f6 d2d4 e7e6 c1g5 f8e7")},
	{"A06", "Réti Opening", SideBlack, split("g1f3 d7d5 e2e3 g8f6 c2c4 e7e6 b2b3 f8e7")},
	{"A06", "Réti Opening", SideBlack, split("g1f3 d7d5 b2b3 g8f6 c1b2 e7e6 e2e3 f8e7")},
	{"A06", "Réti Opening", SideBlack, split("g1f3 d7d5 d2d3 g8f6 g2g3 e7e6 f1g2 f8e7")},
	{"A04", "Réti Opening", SideWhite, split("g1f3 b8c6 d2d4 d7d5 c2c4 e7e6")},
	{"A10", "English Opening", SideWhite, split("c2c4 b8c6 b1c3 e7e5 g2g3 g7g6")},
}

// split turns a space-separated UCI move list into a slice.
func split(s string) []string {
	var out []string
	start := -1
	for i := 0; i <= len(s); i++ {
		if i == len(s) || s[i] == ' ' {
			if start >= 0 {
				out = append(out, s[start:i])
				start = -1
			}
		} else if start < 0 {
			start = i
		}
	}
	return out
}
