// Code generated by cmd/genrwts. DO NOT EDIT.

package rwts

// Addresses are Language Card bank 1 run-time addresses.
const (
	EntryAddr = 0xDC00 // opendir: the read-a-file entry point
	CodeLen   = 495 // driver code bytes
	BlobLen   = 724 // code + denibble tables + site table ($DC00-$DED3)
	TrackD1   = 0xDD8F // self-modifying current-track operand (seed with $41 at boot)
	SlotLoAddr = 0xDEC0 // the site table inside the blob: operand lo bytes...
	SlotHiAddr = 0xDECA // ...and hi bytes (read by m8rwtsinit from bank 1)
	DirBufAddr = 0x1300 // 512-byte directory buffer, main-RAM op-time scratch

	// The driver's zero-page window (saved/swapped around every call
	// by asm/m8.s rwtszp), and its API bytes inside it.
	ZPLo    = 0x3C
	ZPLen   = 0x2C // $3C-$67
	ZPStatus = 0x50 // nonzero after a call = error
	ZPSizeLo = 0x52 // 16-bit read size (block multiple)
	ZPLdrLo  = 0x55 // 16-bit load address
	ZPNamLo  = 0x57 // 16-bit pointer to a length-prefixed name
)

// SlotSites are the operand addresses whose low byte must be OR'd with the
// boot slot (slot<<4, the boot ROM's $2B) before the driver's first call.
var SlotSites = []uint16{0xDC36, 0xDC91, 0xDCE3, 0xDCF2, 0xDD4F, 0xDD62, 0xDD6A, 0xDDB4, 0xDDC2, 0xDDCF}
