// Command gentables generates asm/tables.s: the 0x88 difference-indexed
// attack and direction tables, castling-rights masks, and piece offset
// tables. Run via `make tables` (or `go run ./cmd/gentables` directly).
//
// Difference tables are indexed by (to - from + $77) & $FF for squares in
// 0x88 coordinates. ATTACKTAB holds a bitmask of piece kinds that could
// attack across that difference on an empty board; DELTATAB holds the
// single-step delta (as an unsigned byte) toward `to` for slider rays,
// or 0 if the difference is not on any ray.
package main

import (
	"fmt"
	"math/rand/v2"
	"os"
	"strings"
)

const (
	atkKnight    = 1 << 0
	atkKing      = 1 << 1
	atkDiag      = 1 << 2 // bishop or queen
	atkOrtho     = 1 << 3 // rook or queen
	atkWPawn     = 1 << 4 // white pawn capture (moving up: +$0F/+$11)
	atkBPawn     = 1 << 5 // black pawn capture (moving down: -$0F/-$11)
	tableComment = "; Generated by cmd/gentables. DO NOT EDIT.\n"
)

var (
	knightOffs = []int{-33, -31, -18, -14, 14, 18, 31, 33}
	kingOffs   = []int{-17, -16, -15, -1, 1, 15, 16, 17}
	diagOffs   = []int{-17, -15, 15, 17}
	orthoOffs  = []int{-16, -1, 1, 16}
)

func onBoard(sq int) bool { return sq >= 0 && sq < 128 && sq&0x88 == 0 }

func main() {
	var attack [256]byte
	var delta [256]byte

	for from := range 128 {
		if !onBoard(from) {
			continue
		}
		mark := func(to int, bit byte, step int) {
			if !onBoard(to) {
				return
			}
			idx := (to - from + 0x77) & 0xFF
			attack[idx] |= bit
			if step != 0 {
				delta[idx] = byte(step & 0xFF)
			}
		}
		for _, o := range knightOffs {
			mark(from+o, atkKnight, 0)
		}
		for _, o := range kingOffs {
			mark(from+o, atkKing, 0)
		}
		for _, o := range diagOffs {
			for to := from + o; onBoard(to); to += o {
				mark(to, atkDiag, o)
			}
		}
		for _, o := range orthoOffs {
			for to := from + o; onBoard(to); to += o {
				mark(to, atkOrtho, o)
			}
		}
		mark(from+0x0F, atkWPawn, 0)
		mark(from+0x11, atkWPawn, 0)
		mark(from-0x0F, atkBPawn, 0)
		mark(from-0x11, atkBPawn, 0)
	}

	// Castling-rights mask: rights bits to KEEP when a square is touched
	// (moved from or captured on). Bits: 1=WK, 2=WQ, 4=BK, 8=BQ.
	var castleMask [128]byte
	for i := range castleMask {
		castleMask[i] = 0x0F
	}
	castleMask[0x04] = 0x0C // e1: white loses both
	castleMask[0x00] = 0x0D // a1: white loses queenside
	castleMask[0x07] = 0x0E // h1: white loses kingside
	castleMask[0x74] = 0x03 // e8: black loses both
	castleMask[0x70] = 0x07 // a8: black loses queenside
	castleMask[0x77] = 0x0B // h8: black loses kingside

	// ---- Derived table data. Computation order is load-bearing only
	// inside buildZobrist (its PRNG stream fixes every key value); the
	// emission ORDER further down is a pure layout choice — see the
	// LAYOUT note there.

	// SLOTTAB[b] = piece-list slot for piece byte b: index | (color ? 16 : 0).
	var slotTab [256]byte
	for i := range slotTab {
		s := i >> 4
		if i&8 != 0 {
			s |= 16
		}
		slotTab[i] = byte(s)
	}

	// TYPEATK2[piece&$0F] = the attack bit this piece contributes.
	// Pawns get their color's direction bit, so wrong-direction pawns
	// fast-reject through the same AND as every other piece — no
	// special case in attacked().
	var typeAtk2 [16]byte
	atkBits := []byte{0, 0 /*per color below*/, atkKnight, atkDiag, atkOrtho, atkDiag | atkOrtho, atkKing, 0}
	for typ := 1; typ <= 6; typ++ {
		typeAtk2[typ] = atkBits[typ]
		typeAtk2[8|typ] = atkBits[typ]
	}
	typeAtk2[1] = atkWPawn
	typeAtk2[8|1] = atkBPawn

	// Pawn-structure tables (pawnterm's rank-bitmask form). Per file,
	// pawnterm builds an 8-bit mask of occupied ranks; these tables
	// turn one mask into the derived quantities directly:
	//   RANKBIT[sq]   = 1 << rank (0x88-indexed board square)
	//   WBLOCKM[bits] = ranks >= the most advanced white pawn (its own
	//                   rank included: an adjacent same-rank enemy pawn
	//                   blocks, matching the old >= compare)
	//   WPASSB[bits]  = PASSEDBONUS[rank of most advanced white pawn]
	//   BBLOCKM[bits] = ranks <= the most advanced black pawn (ditto <=)
	//   BPASSB[bits]  = PASSEDBONUS[7 - that rank]
	// The passed-pawn bonus weights live HERE now. Values are the
	// Texel-tuned set from the Go mirror, re-tuned on the diversified
	// (real-opponent) corpus: self-play overvalued advanced passed pawns,
	// corrected down ~20-25%. Asm rig confirms do-no-harm (+8.1 +/- 22.4
	// over 600 games); see docs/results.md.
	//
	// The table looks non-monotone (index 6, a 7th-rank passer, scores 20
	// while index 5 scores 52) and is NOT: it is a top-up on the PeSTO
	// pawn PSQT, which alone pays +81.6 EG between the 6th and 7th ranks,
	// so PSQT+bonus rises monotonically from the 4th rank up
	// (mirror TestPassedEffectiveCurve). Investigated 2026-07-25: the
	// corpus constrains every bucket (5-10% of 108,908 rows each), a free
	// re-tune reproduces these exact values, and three monotone
	// replacements screened +3/-3/-6 Elo. Don't "fix" it again.
	passedBonus := []int{0, 15, 0, 21, 50, 52, 20, 0}
	var rankBit [128]byte
	for sq := range rankBit {
		if sq&0x88 == 0 {
			rankBit[sq] = 1 << (sq >> 4)
		}
	}
	var wBlockM, wPassB, bBlockM, bPassB [256]byte
	for bits := 1; bits < 256; bits++ {
		hi := 7
		for bits&(1<<hi) == 0 {
			hi--
		}
		lo := 0
		for bits&(1<<lo) == 0 {
			lo++
		}
		wBlockM[bits] = byte(0xFF << hi)
		wPassB[bits] = byte(passedBonus[hi])
		bBlockM[bits] = byte(1<<(lo+1) - 1)
		bPassB[bits] = byte(passedBonus[7-lo])
	}

	// DBLTAB[bits] = 12 if the file holds two or more pawns (the flat
	// doubled-pawn penalty magnitude; pawnterm applies the sign), else 0.
	// Keyed on a side's per-file rank mask; replaces the inline
	// bits&(bits-1) test in the unrolled pawnterm file walk.
	var dblTab [256]byte
	for bits := 1; bits < 256; bits++ {
		if bits&(bits-1) != 0 {
			dblTab[bits] = 12
		}
	}

	// Per-file pawn-term cache support (deep optimization review r4
	// integration pass): FILEBIT[sq] = 1 << file for on-board 0x88
	// squares (make's tail marks changed files into FDIRTY with it);
	// SPREADTAB[b] = b | b<<1 | b>>1 widens a changed-files mask to the
	// files whose per-file terms could be affected (each file's
	// doubled/isolated/passed terms read files f-1..f+1 of both sides).
	var fileBit [128]byte
	for sq := range fileBit {
		if sq&0x88 == 0 {
			fileBit[sq] = 1 << (sq & 7)
		}
	}
	var spreadTab [256]byte
	for i := range spreadTab {
		spreadTab[i] = byte(i | i<<1 | i>>1)
	}

	// Quarter-square multiply tables for the taper (eval's evmul):
	// SQRLO/HI[i] = floor(i*i/4), ISQLO/HI[i] = floor((i-32)*(i-32)/4).
	// a*b = f(a+b) - f(a-b) (exact for integers: a+b and a-b share
	// parity). eval self-modifies the operand low byte to a (a byte of
	// |MG-EG|) and indexes with Y = w (0..32, PHASEWX's capped weight)
	// and X = 32-w, so SQR reads index a+w (max 255+32 = 287) and ISQ
	// reads a-w+32 (max 255+31 = 286); 512 entries cover both with room,
	// page-aligned for abs,y.
	var sqrLo, sqrHi, isqLo, isqHi [512]byte
	for i := range 512 {
		q := i * i / 4
		sqrLo[i], sqrHi[i] = byte(q), byte(q>>8)
		d := i - 32
		q = d * d / 4
		isqLo[i], isqHi[i] = byte(q), byte(q>>8)
	}

	// TT addressing: TTPTR = TTBASE + index*8, index = (HASH1&0x0F)<<8 | HASH0.
	// SHL3TAB/SHR5TAB split HASH0*8 across the pointer bytes; TTHITAB puts
	// HASH1's nibble in bits 3-6. Page-aligned so lda abs,x never crosses.
	var shl3Tab, shr5Tab, ttHiTab [256]byte
	for i := range shl3Tab {
		shl3Tab[i] = byte(i << 3)
		shr5Tab[i] = byte(i >> 5)
		ttHiTab[i] = byte((i & 0x0F) << 3)
	}

	// PHASEWX[phase] = the /32 taper weight, with the >= 24 cap baked in
	// (promotions can push PHASE past 24; the absolute ceiling, 9 queens
	// + 2 rooks + 2 minors per side, is 88). Page-aligned so eval indexes
	// PHASE directly with no cap compare.
	var phaseWX [256]byte
	for p := range 256 {
		c := min(p, 24)
		phaseWX[p] = byte((c*32 + 12) / 24)
	}

	zob := buildZobrist()

	// ------------------------------------------------------------------
	// LAYOUT (space optimization round 1, 2026-07-25). TABLES is bigger
	// than all the engine's code, and it had never been packed: `.align`
	// directives left 977 bytes of pure fill scattered through it (240 B
	// after TYPEATK2, 232 after PHASEVAL, 137 after RATTACK, 128 each
	// after WBLOCKM and FILEBIT, 104 after ORTHOOFF). The tables are now
	// grouped so that every alignment boundary falls exactly on the end
	// of a group, and ALL the small unaligned tables (plus hashstm) are
	// packed into one run at the tail:
	//
	//   A  12 x 256 B page-aligned tables, back to back   (3072, 0 fill)
	//   B  the four 512 B quarter-square tables           (2048, 0 fill)
	//   C  RANKBIT(128) + WBLOCKM(256) + FILEBIT(128)     ( 512, 0 fill)
	//   D  PSQT: 12 pages                                 (3072, 0 fill)
	//   E  ZKEYS: 24 pages                                (6144, 0 fill)
	//   F  CASTLEMASK(128) + every unaligned small table  ( 413, 0 fill)
	//
	// Each group's size is a multiple of 256, so the `.align 256` at each
	// boundary is a no-op that documents (and enforces) the invariant.
	//
	// CYCLE-IDENTITY RULE for anything added here: an `abs,x`/`abs,y`
	// read costs +1 cycle when base+index crosses a page, so every table
	// must keep the page-crossing behaviour it had. Page-aligned tables
	// indexed 0..255 (group A) and 0..127 (RANKBIT/FILEBIT/CASTLEMASK at
	// offset $00/$80) never cross; WBLOCKM keeps its offset $80 (it is
	// indexed 0..255 and DOES cross, as before); the group-F smalls are
	// each laid out so their whole indexed range sits inside one page.
	// TestTablePacking (internal/chesstest) asserts all of this.
	// ------------------------------------------------------------------
	var b strings.Builder
	b.WriteString(tableComment)
	b.WriteString("\n.segment \"TABLES\"\n")

	// ---- group A: exactly-256-byte page-aligned tables ----
	b.WriteString("\n.align 256\n")
	emit(&b, "ATTACKTAB", attack[:])
	emit(&b, "DELTATAB", delta[:])
	emit(&b, "SLOTTAB", slotTab[:])
	emit(&b, "WPASSB", wPassB[:])
	emit(&b, "BBLOCKM", bBlockM[:])
	emit(&b, "BPASSB", bPassB[:])
	emit(&b, "DBLTAB", dblTab[:])
	emit(&b, "SPREADTAB", spreadTab[:])
	emit(&b, "SHL3TAB", shl3Tab[:])
	emit(&b, "SHR5TAB", shr5Tab[:])
	emit(&b, "TTHITAB", ttHiTab[:])
	emit(&b, "PHASEWX", phaseWX[:])

	// ---- group B: quarter-square multiply tables (512 B each) ----
	b.WriteString("\n.align 256\n")
	emit(&b, "SQRLO", sqrLo[:])
	emit(&b, "SQRHI", sqrHi[:])
	emit(&b, "ISQLO", isqLo[:])
	emit(&b, "ISQHI", isqHi[:])

	// ---- group C: the 128-byte square table + WBLOCKM at offset $80 ----
	b.WriteString("\n.align 256\n")
	emit(&b, "RANKBIT", rankBit[:])
	emit(&b, "WBLOCKM", wBlockM[:])
	emit(&b, "FILEBIT", fileBit[:])

	// ---- group D: PSQT planes ----
	b.WriteString("\n.align 256\n")
	emitPSQT(&b)

	// ---- group E: Zobrist piece-square planes ----
	b.WriteString("\n.align 256\n")
	emit(&b, "ZKEYS", zob.keys[:])

	// ---- group F: CASTLEMASK + every unaligned small table ----
	b.WriteString("\n.align 256\n")
	emit(&b, "CASTLEMASK", castleMask[:])
	emit(&b, "TYPEATK2", typeAtk2[:])
	emitInts(&b, "KNIGHTOFF", knightOffs)
	emitInts(&b, "KINGOFF", kingOffs)
	emitInts(&b, "DIAGOFF", diagOffs)
	emitInts(&b, "ORTHOOFF", orthoOffs)
	emitPSQTPages(&b)
	emitZobristSmall(&b, zob)
	emitMopup(&b)

	if err := os.WriteFile("asm/tables.s", []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// emitMopup writes the FT2_MOPUP endgame mop-up material table (part of
// the group-F run of unaligned small tables).
//
// MOPMATLO/MOPMATHI[8]: material value per piece type (index 0 empty,
// 1..6 = P N B R Q K, 7 unused) as a 16-bit little-endian pair, exactly
// mirror mopMatVal / vicVal {0,100,320,330,500,975,0,0}. Drives the signed
// material-edge gate (winning side leads by >= a rook = 450).
//
// The centre-manhattan corner-distance (mirror mopupCMD: 0 centre .. 6
// corner) is NOT a table here: when the term was ported the image had only
// ~240 free bytes and a 64-byte table plus the routine overflowed MAIN, so
// mopupterm computes it
// inline as cornerdist(file)+cornerdist(rank) with cornerdist(c in 0..7) =
// (c>=4)? c&3 : (~c)&3 -> {3,2,1,0,0,1,2,3}. That reproduces mopupCMD's
// values exactly; TestMopupEvalParity verifies the resulting eval to the
// centipawn over the endgame positions where the term fires.
func emitMopup(b *strings.Builder) {
	mat := [8]int{0, 100, 320, 330, 500, 975, 0, 0}
	var lo, hi [8]byte
	for i, v := range mat {
		lo[i], hi[i] = byte(v), byte(v>>8)
	}
	emit(b, "MOPMATLO", lo[:])
	emit(b, "MOPMATHI", hi[:])
}

func emit(b *strings.Builder, name string, data []byte) {
	fmt.Fprintf(b, "%s:\n", name)
	for i := 0; i < len(data); i += 16 {
		b.WriteString("        .byte ")
		for j := i; j < i+16 && j < len(data); j++ {
			if j > i {
				b.WriteString(",")
			}
			fmt.Fprintf(b, "$%02X", data[j])
		}
		b.WriteString("\n")
	}
}

// emitPSQT writes the tapered piece-square tables in the engine's layout:
// for piece type t (1-6), a 512-byte block at PSQTBASE+(t-1)*512 holding
// MGLO[sq88] at +0, MGHI at +128, EGLO at +256, EGHI at +384. Values are
// white-POV with piece base values baked in; black uses sq^$70 and
// subtracts. TYPEPAGE0/1 give each type's table page for (zp),y access;
// they are emitted as link-time expressions on PSQTBASE.
func emitPSQT(b *strings.Builder) {
	b.WriteString("PSQTBASE:\n")
	for t := range 6 {
		var mglo, mghi, eglo, eghi [128]byte
		for sq := range 128 {
			if sq&0x88 != 0 {
				continue
			}
			rank := sq >> 4
			file := sq & 7
			idx := (7-rank)*8 + file // PeSTO tables are a8-first
			mg := pestoPieceMG[t] + pestoMG[t][idx]
			eg := pestoPieceEG[t] + pestoEG[t][idx]
			mglo[sq] = byte(mg & 0xFF)
			mghi[sq] = byte(mg >> 8 & 0xFF)
			eglo[sq] = byte(eg & 0xFF)
			eghi[sq] = byte(eg >> 8 & 0xFF)
		}
		names := []string{"PAWN", "KNIGHT", "BISHOP", "ROOK", "QUEEN", "KING"}
		emit(b, fmt.Sprintf("PSQT_%s_MGLO", names[t]), mglo[:])
		emit(b, fmt.Sprintf("PSQT_%s_MGHI", names[t]), mghi[:])
		emit(b, fmt.Sprintf("PSQT_%s_EGLO", names[t]), eglo[:])
		emit(b, fmt.Sprintf("PSQT_%s_EGHI", names[t]), eghi[:])
	}
}

// emitPSQTPages writes the group-F companions of the PSQT block: the
// per-type table-page pointers (link-time expressions on PSQTBASE) and
// the per-type phase contribution.
func emitPSQTPages(b *strings.Builder) {
	// Table page pointers, indexed by piece type 1-6 (0 and 7 unused).
	b.WriteString("TYPEPAGE0:\n        .byte 0")
	for t := range 6 {
		fmt.Fprintf(b, ", >PSQTBASE+%d", t*2)
	}
	b.WriteString(", 0\nTYPEPAGE1:\n        .byte 0")
	for t := range 6 {
		fmt.Fprintf(b, ", >PSQTBASE+%d", t*2+1)
	}
	b.WriteString(", 0\n")
	// Phase contribution per piece type.
	b.WriteString("PHASEVAL:\n        .byte 0,0,1,1,2,4,0,0\n")
}

// zobrist holds the generated Zobrist key material. The PRNG draw order
// (piece-square planes, then side-to-move, then 16 castling-rights keys,
// then 8 ep-file keys) is LOAD-BEARING — it fixes every key value, and
// the hash-parity tests pin those values — so it is kept exactly as it
// was when the keys were first generated, independently of the layout
// order the tables are emitted in.
type zobrist struct {
	keys     [12 * 512]byte
	stm      [4]byte
	castling [16][4]byte
	ep       [8][4]byte
}

// buildZobrist draws all key material. ZKEYS is kind-major: ZKEYS +
// kind*512 holds plane0[128] plane1[128] plane2[128] plane3[128] for that
// kind (white P..K = kinds 0-5, black = 6-11, 0x88 squares). Every block
// starts on a page boundary, so a pointer to it has lo byte 0 — the ZPTR
// invariant established in evalinit.
func buildZobrist() *zobrist {
	rnd := rand.New(rand.NewPCG(0x6502c4e5, 0x0a11babe))
	key := func() [4]byte {
		v := rnd.Uint32()
		return [4]byte{byte(v), byte(v >> 8), byte(v >> 16), byte(v >> 24)}
	}
	z := &zobrist{}
	for kind := range 12 {
		for sq := range 128 {
			if sq&0x88 != 0 {
				continue
			}
			k := key()
			for p := range 4 {
				z.keys[kind*512+p*128+sq] = k[p]
			}
		}
	}
	z.stm = key()
	for i := range z.castling {
		z.castling[i] = key()
	}
	for i := range z.ep {
		z.ep[i] = key()
	}
	return z
}

// emitZobristSmall writes the group-F Zobrist companions: ZKHI0[piece&$0F]
// (the piece's ZKEYS block page, so the hash update needs no multiply),
// the DIRTYTAB/TYPEPG0X/TYPEPG1X/PHASEV16 piece&$0F-indexed tables for the
// fused make-path updates, and the side-to-move / castling / ep keys plus
// the unrolled hashstm routine.
func emitZobristSmall(b *strings.Builder, z *zobrist) {
	// The piece&$0F-indexed tables (color bit 3 + type bits 0-2).
	pieceIdx := func(name string, val func(typ, kind int) string) {
		fmt.Fprintf(b, "%s:\n        .byte ", name)
		for i := range 16 {
			if i > 0 {
				b.WriteString(",")
			}
			typ := i & 7
			if typ < 1 || typ > 6 {
				b.WriteString("0")
				continue
			}
			kind := typ - 1
			if i&8 != 0 {
				kind += 6
			}
			b.WriteString(val(typ, kind))
		}
		b.WriteString("\n")
	}
	pieceIdx("ZKHI0", func(typ, kind int) string {
		return fmt.Sprintf(">ZKEYS+%d", kind*2)
	})
	pieceIdx("DIRTYTAB", func(typ, kind int) string {
		// Any nonzero entry invalidates PSTRUCT. Bit 7 additionally
		// marks pawns so movepiece/takepiece can bmi to the pawn-file
		// bitmask maintenance (PWBITS/PBBITS toggles) at no cost to
		// the non-pawn fast path. Bit 0 (set by BOTH kinds) is the
		// per-make transient "THIS move dirtied" bit: make's tail
		// tests it with one lsr and strips it (lazy pawnterm, deep
		// opt r4 integration), so a deferred stale marker riding in
		// PDIRTY across makes is distinguishable from fresh dirt.
		// After the lsr, exactly the king-only pattern ($03) gives 1,
		// the ptkonly dispatch key.
		switch typ {
		case 1: // pawn
			return "$81"
		case 6: // king
			return "3"
		}
		return "0"
	})
	pieceIdx("TYPEPG0X", func(typ, kind int) string {
		return fmt.Sprintf(">PSQTBASE+%d", (typ-1)*2)
	})
	pieceIdx("TYPEPG1X", func(typ, kind int) string {
		return fmt.Sprintf(">PSQTBASE+%d", (typ-1)*2+1)
	})
	phaseVals := []int{0, 0, 1, 1, 2, 4, 0, 0}
	pieceIdx("PHASEV16", func(typ, kind int) string {
		return fmt.Sprintf("%d", phaseVals[typ])
	})

	fmt.Fprintf(b, "STMKEY:\n        .byte $%02X,$%02X,$%02X,$%02X\n",
		z.stm[0], z.stm[1], z.stm[2], z.stm[3])
	// Unrolled side-to-move hash update (runs on every make/unmakenull;
	// the immediate forms halve the looped version's cost).
	b.WriteString("hashstm:\n")
	for i, kb := range z.stm {
		fmt.Fprintf(b, "        lda HASH%d\n        eor #$%02X\n        sta HASH%d\n", i, kb, i)
	}
	b.WriteString("        rts\n")
	// Castling keys: one 4-byte key per rights nibble value.
	b.WriteString("CASTKEYS:\n")
	for _, k := range z.castling {
		fmt.Fprintf(b, "        .byte $%02X,$%02X,$%02X,$%02X\n", k[0], k[1], k[2], k[3])
	}
	// EP keys: by file; plus EPNONE = 0 handled by skipping the xor.
	b.WriteString("EPKEYS:\n")
	for _, k := range z.ep {
		fmt.Fprintf(b, "        .byte $%02X,$%02X,$%02X,$%02X\n", k[0], k[1], k[2], k[3])
	}
}

func emitInts(b *strings.Builder, name string, offs []int) {
	fmt.Fprintf(b, "%s:\n        .byte ", name)
	for i, o := range offs {
		if i > 0 {
			b.WriteString(",")
		}
		fmt.Fprintf(b, "$%02X", byte(o&0xFF))
	}
	b.WriteString("\n")
}
